### ISSUE TITLE
Error to install PyKCS11 1.5.11 in Ubuntu 22.04

### ISSUE THREAD

**Issue by igallart** [LudovicRousseau/PyKCS11#100]
Hello, I have tried to install the package through PIP and downloaded the package, but it gives the same error, that it cannot find vector.h. It's python 3.6 compiled from the sources on Ubuntu 22.04 using clang, because with gcc it's not possible to compile python 3.6 on Ubuntu 22.04. Everything works perfectly except for this package that cannot be installed. Any idea of what it could be?

igallart@ubuntu:~/PyKCS11-1.5.11$ ~/sources/venv/odoo130/bin/python3.6 setup.py install
running install
running bdist_egg
running egg_info
writing PyKCS11.egg-info/PKG-INFO
writing dependency_links to PyKCS11.egg-info/dependency_links.txt
writing top-level names to PyKCS11.egg-info/top_level.txt
file PyKCS11/LowLevel.py (for module PyKCS11.LowLevel) not found
reading manifest file 'PyKCS11.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'COPYING'
writing manifest file 'PyKCS11.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'PyKCS11._LowLevel' extension
swigging src/pykcs11.i to src/pykcs11_wrap.cpp
swig -python -c++ -o src/pykcs11_wrap.cpp src/pykcs11.i
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc -I/usr/local/include -I/home/igallart/sources/venv/odoo130/include -I/home/igallart/sources/python-3.6.15/include/python3.6m -c src/ck_attribute_smart.cpp -o build/temp.linux-x86_64-3.6/src/ck_attribute_smart.o
In file included from src/ck_attribute_smart.cpp:17:
src/stdafx.h:26:10: fatal error: 'vector' file not found
#include <vector>
         ^~~~~~~~
1 error generated.
error: command 'clang' failed with exit status 1

**Comment by LudovicRousseau** [comment]
You have a custom setup with Python installed in `/home/igallart/sources/python-3.6.15/`?

It is `vector` not `vector.h`. This file is provided by [libstdc++-10-dev](https://packages.ubuntu.com/kinetic/amd64/libstdc++-10-dev/filelist)

**Comment by igallart** [comment]
> You have a custom setup with Python installed in `/home/igallart/sources/python-3.6.15/`?
> 
> It is `vector` not `vector.h`. This file is provided by [libstdc++-10-dev](https://packages.ubuntu.com/kinetic/amd64/libstdc++-10-dev/filelist)

@LudovicRousseau ,that was it, thank you very much. I installed the https://packages.ubuntu.com/jammy-updates/libstdc++-12-dev package.
