### ISSUE TITLE
How do I use PyKCS11 to connect and sign via **epass3003 token**?

### ISSUE THREAD

**Issue by mohammadreza1408** [LudovicRousseau/PyKCS11#105]
# Your system information

* Operating system used: Windows10
* PyKCS11 version: 1.5.12
* Python version: 3.10
* PKCS#11 library used: PyKCS11

# Please describe your issue in as much detail as possible:
I use the PyKCS11 library to use the epass3003auto token
And I want to use a signature
My signature algorithm is RSA2048 version 1.5 SHA256
The output I get from this library is different from the output of similar programs in other programming languages (developed by others, such as Java and C#), while I give it the same input.
Can you help me solve this problem?

# Steps for reproducing this issue:
 To connect to the epass3003 token after a lot of googling I found out that I need to use a DLL called **ShuttleCsp11_3003.dll**.
**ShuttleCsp11_3003.dll** is what is used in C# and Java programs developed by others to connect to the epass3003 token.
thank you very much

**Comment by LudovicRousseau** [comment]
Why do you think it is a problem in PyKCS11?

I suggest to use/modify https://github.com/LudovicRousseau/PyKCS11/blob/master/samples/signature.py

**Comment by LudovicRousseau** [comment]
No feedback from user.
Closing.
