### ISSUE TITLE
CKA_VALUE of public key DER format

### ISSUE THREAD

**Issue by msetina** [LudovicRousseau/PyKCS11#109]
I am trying to get public key from a card and was succesfull reading CKA_VALUE from 384 bit EC public key. Got 99 bytes and sent it to cryptography  load_der_public_key. It reports that it can not be read:
Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters). Details: ASN.1 parsing error: unexpected tag (got Tag { value: 4, constructed: false, class: Universal })

**Comment by msetina** [comment]
I have ckecked CKA_SENSITIVE and it is False.

**Comment by LudovicRousseau** [comment]
Why do you think it is a bug in PyKCS11?

**Comment by msetina** [comment]
I am not posting as a bug, but as an issue. Wills close it.
