### ISSUE TITLE
CKR_FUNCTION_NOT_SUPPORTED error

### ISSUE THREAD

**Issue by mlakewood** [LudovicRousseau/PyKCS11#11]
Hi all,

Im using a YubiKey with a PIV on it and when using this library it seems to be able to get at the YubiKey but then fails with something like this.

```
Traceback (most recent call last):
  File "test.py", line 58, in <module>
    (pubKey, privKey) = session.generateKeyPair(pubTemplate, privTemplate)
  File "/Users/mlakewood/projects/yubi_key/venv/lib/python3.5/site-packages/PyKCS11/__init__.py", line 1321, in generateKeyPair
    raise PyKCS11Error(rv)
PyKCS11.PyKCS11Error: CKR_FUNCTION_NOT_SUPPORTED (0x00000054)
```

I've tried both the encrypt.py sample and the generate.py sample and both as soon as they try to do some kind of cryptography fail with the above. Interestingly it will accept the PIN, so the communication is there.

Any help would be greatly appreciated.

Cheers

Mark

**Comment by mlakewood** [comment]
I have the same failure on both python2.7 and python3.5

**Comment by LudovicRousseau** [comment]
It looks like your YubiKey and/or the associated PKCS#11 library does not support C_GenerateKeyPair().

What version of PyKCS11 are you using?

**Comment by mlakewood** [comment]
Currently running PyKCS11==1.4.1  on OS X 10.11.6. Is there any other debug information I can gather to work out what is missing here?

**Comment by mlakewood** [comment]
Thanks for the quick response btw!

**Comment by LudovicRousseau** [comment]
This error is returned by the PKCS#11 library you are using, not by PyKCS11.

You should complain to the PKCS#11 library maintainer (YubiKey?)
