### ISSUE TITLE
Any chance for SignRecover and VerifyRecover?

### ISSUE THREAD

**Issue by msetina** [LudovicRousseau/PyKCS11#110]
I am going over operations in PKCS11 and found SignRecover and VerifyRecover, but I can not find equivalent functions implemented here. Is there a plan for them?

https://crypto.stackexchange.com/questions/24294/how-do-signrecover-and-verifyrecover-work

**Comment by LudovicRousseau** [comment]
I never used these functions: `C_SignRecover()` & `C_VerifyRecover()`
It should not be too difficult to add support in PyKCS11.

Do you use a PKSC#11 library that implements them?

**Comment by msetina** [comment]
I don't. I saw implementation on RSA key of cryptography and was wondering if PKCS11 has an equivalent.

**Comment by LudovicRousseau** [comment]
These functions are **not** implemented in SoftHSM https://github.com/opendnssec/SoftHSMv2/blob/develop/src/lib/SoftHSM.cpp#L4896
It will be difficult to test and debug.

I propose you to ask again when I can use SoftHSM to validate PyKCS11 code for `C_SignRecover()` & `C_VerifyRecover()`.

**Comment by msetina** [comment]
I was looking into the same thing. Sadly....

**Comment by msetina** [comment]
I was pointed out on the SoftHSM2 project, that development is contstrained and the probability of new features is low. This has implications on features like this.
