### ISSUE TITLE
Session over scriptruntime

### ISSUE THREAD

**Issue by jonas99y** [LudovicRousseau/PyKCS11#12]
Is it somehow possible to keep a session object form pkcs11.openSession( ) over the runtime of a script?
So the session.login is only called once.

**Comment by LudovicRousseau** [comment]
I am not sure to understand what you want to do.
Please explain.

**Comment by jonas99y** [comment]
I just want to create a session once, with the first run of the script and then use the same session in the next run of the script.

**Comment by LudovicRousseau** [comment]
That is not possible.
You can design a client/server architecture and load the PKCS#11 library in the server. But that is out of scope for PyKCS11.
