### ISSUE TITLE
Multiple Objects for different PKCS11-Libraries

### ISSUE THREAD

**Issue by clk-jkn** [LudovicRousseau/PyKCS11#124]
# Your system information

* Operating system used: Ubuntu 22.04
* PyKCS11 version: 1.5.16
* Python version: Python 3.10.12
* PKCS#11 library used: SoftHSM and OpenSC

# Please describe your issue in as much detail as possible:
What I expected to happen:
I created two different Objects and called load() with Paths to different PKCS#11-Libraries on each of them. I expected to be able to communicate with either PKCS#11-Library just by calling the Function on the respective object.

What actually happend:
I get the same Token-Info from both objects, even though I loaded two different libraries. It seems like the load() is global and the last load wins. Would it be possible to make load() only affect the object it was called on? Thank you for your work, even if it is not feassible to add this functionality!

# Steps for reproducing this issue:

1.  Import PyKCS11:
`from PyKCS11 import *`
2.  Create two Objects:
```python
pkcs11_1 = PyKCS11Lib()
pkcs11_2 = PyKCS11Lib()
```
3. Call load() on both of them with different paths:
```python
pkcs11_1.load('Path to opensc.so')
pkcs11_2.load('Path to softhsm.so')
```
4. Check TokenInfo:
```python
print(pkcs11_1.getTokenInfo(0))
print(pkcs11_2.getTokenInfo(0))
```
The Token-Info is the same for both calls.

**Comment by LudovicRousseau** [comment]
What you are trying to do _should_ work.

Can you try again with the current code in git?
A bug was fixed in https://github.com/LudovicRousseau/PyKCS11/commit/663565a053f401b6979a68ff43a351ec6b406f4d but is not yet included in a released version.

**Comment by clk-jkn** [comment]
I will see if I can install the current git code. Will report as soon as I managed. Thanks

**Comment by clk-jkn** [comment]
That is indeed it 👍 The current code in git works as expected! Thanks a bunch

**Comment by LudovicRousseau** [comment]
Good.
I will make a new release "soon".

**Comment by LudovicRousseau** [comment]
Version 1.5.17 now available https://github.com/LudovicRousseau/PyKCS11/releases/tag/1.5.17

**Comment by clk-jkn** [comment]
Many thanks!
