### ISSUE TITLE
Support CK_INVALID_HANDLE as hKey parameter of C_EncryptInit

### ISSUE THREAD

**Issue by 31z4** [LudovicRousseau/PyKCS11#13]
Now `C_EncryptInit` expects only `CK_OBJECT_HANDLE` instance as its `hKey` paramterer. But some vendors implementations allow and expect `CK_INVALID_HANDLE ` there. Supporting it would be great!

**Comment by LudovicRousseau** [comment]
I have not changed the way ``encrypt()`` works. Why to you use *now*?

How do you specify the key to use if you use ``CK_INVALID_HANDLE``?

**Comment by LudovicRousseau** [comment]
Also why didn't you use the issue template to report the issue?

You should have seen https://github.com/LudovicRousseau/PyKCS11/blob/master/.github/ISSUE_TEMPLATE.md while creating the issue.

**Comment by 31z4** [comment]
Sorry about not using the template.
We're using a proprietary library that implements PKCS#11 interface with some custom mechanisms. And we cannot use `encrypt()`. We have to use low level `C_EncryptInit `, and `C_EncryptUpdate `.
It turned out that `CK_OBJECT_HANDLE()` works for us.
