### ISSUE TITLE
signing with CKM_RSA_PKCS_PSS fails with "Segmentation fault"

### ISSUE THREAD

**Issue by l-g-s** [LudovicRousseau/PyKCS11#14]
#### Your system information

* PyKCS11 version: nCipher PKCS#11 2.19.1, cryptokiVersion: 2.1
* Python version: 2.7.6

#### Please describe your issue in as much detail as possible:
I was trying to sign some data using a RSA-4096 key and **CKM_RSA_PKCS_PSS** as mechanism but calling of sign() function aborts with a "Segmentation fault":

```
data = "a932d16a6b0a383b873aa73e7bbe56631924775abd69e8ec5265d5719a4df37d9300f3217aaf078139b4fbe403c3800e" # SHA-384 of a file
signature = session.sign(privKey, binascii.unhexlify(data), PyKCS11.Mechanism(PyKCS11.CKM_RSA_PKCS_PSS)) 
```

The behavior is the same for all CKM_RSA_PKCS_PSS mechanisms (e.g. also for CKM_SHA384_RSA_PKCS_PSS) although they get listed for the selected slot by getMechanismList(). 

Using a "regular" CKM_RSA_PKCS mechanism returns the signature as expected -- it only fails when PSS padding is involved.

According to the API it should be possible to provide specific parameters for a mechanism but I'm not sure how to properly make the call:

`mechanism = PyKCS11.Mechanism(PyKCS11.CKM_RSA_PKCS_PSS, param=(PyKCS11.CKM_SHA384, PyKCS11.CKG_MGF1_SHA384, 48))`

...fails with "ValueError: byte must be in range(0, 256)" (as CKM_SHA384 equals 608). 
I noticed that LowLevel.py defines a class "CK_RSA_PKCS_OAEP_PARAMS" (with attributes "hashAlg", "mgf" and others) but I couldn't find a class for "CK_RSA_PKCS_PSS_PARAMS" (with expected attributes "hashAlg", "mgf" and "sLen".

**Could it be that support for PSS is missing or is it me who's using it wrong?**

#### Steps for reproducing this issue:

1. get list of available slots: getSlotList()
2. read slot info to find a slot with CKF_TOKEN_PRESENT: getSlotInfo(slot)
3. open appropriate session: session = pkcs11.openSession(slot, PyKCS11.CKF_SERIAL_SESSION)
4. find CKO_PRIVATE_KEY object: privKey = session.findObjects(...)[0]
5. call signing function as described above

Best Regards
Lars

**Comment by LudovicRousseau** [comment]
PyKCS11 does not yet support ``CKM_RSA_PKCS_PSS``.
I guess I will need to use a special code as for ``CK_RSA_PKCS_OAEP_PARAMS`` https://github.com/LudovicRousseau/PyKCS11/blob/master/PyKCS11/__init__.py#L744

I will need your help to test the new code.

**Comment by LudovicRousseau** [comment]
I implemented (but not tested) ``CKM_RSA_PKCS_PSS`` support in https://github.com/LudovicRousseau/PyKCS11/tree/devel

Can you check this branch **devel** works for you?

**Comment by LudovicRousseau** [comment]
I forgot, you have a code sample at https://github.com/LudovicRousseau/PyKCS11/blob/devel/tests/test_asymetric.py#L96

**Comment by l-g-s** [comment]
With your latest change in the \_\_init\_\_.py (af4fe2b) I was able to build and test your extensions.
I succeeded to sign and verify some data (a precalculated SHA-384 hash) using CKM_RSA_PKCS_PSS as mechanism as shown in your sample code linked above.
Thank you very much fur your immediate support!

**Comment by LudovicRousseau** [comment]
Thanks for your feedback.
Fixed in https://github.com/LudovicRousseau/PyKCS11/commit/13917dad0aa4a077a892f403a9355565db9de8d1
