### ISSUE TITLE
run_test.py is not packaged in the release tarball

### ISSUE THREAD

**Issue by Jakuje** [LudovicRousseau/PyKCS11#15]
#### Your system information
* PyKCS11 version: 1.4.3
* Python version: 2.7.13

#### Please describe your issue in as much detail as possible:
The latest tarball downloaded from sourceforge
https://sourceforge.net/projects/pkcs11wrap/files/pykcs11/pykcs11-1.4.3/
```
$ tar -t -f PyKCS11-1.4.3.tar.gz  | grep run_test
[no result]
```

#### Steps for reproducing this issue:

1. Download the tarball from SF
2. List the files tar -t -f PyKCS11-1.4.3.tar.gz  | grep run_test
3. See there is no `run_test.py` file

**Comment by LudovicRousseau** [comment]
thanks.
Fixed in https://github.com/LudovicRousseau/PyKCS11/commit/896c20cdefb4fd5df529bc47a79aff4f258ba033
