### ISSUE TITLE
CKR_ARGUMENTS_BAD When Running rsa_encrypt.py

### ISSUE THREAD

**Issue by jordan-wright** [LudovicRousseau/PyKCS11#16]
#### Your system information

* PyKCS11 version: master
* Python version: 3.6.2

#### Please describe your issue in as much detail as possible:

*Expected* 

When I run the `rsa_encrypt.py` script using SoftHSM as the backend HSM emulator, I expect to see the test string successfully encrypted using the `RSAOAEPMechanism` mechanism.

*Results*

I receive the following Traceback:

```
Traceback (most recent call last):
  File "rsa_encrypt.py", line 60, in <module>
    ciphertext = session.encrypt(pubKey, pt, mech)
  File "/usr/local/lib/python3.6/site-packages/PyKCS11/__init__.py", line 1092, in encrypt
    raise PyKCS11Error(rv)
PyKCS11.PyKCS11Error: CKR_ARGUMENTS_BAD (0x00000007)
```

It's unclear what's causing the error. At first, I thought that maybe it'd be a bad parameter when setting up the mechanism, but that _seems_ fine.

#### Steps for reproducing this issue:

For reference, I'm using [this Docker](https://hub.docker.com/r/bruienne/pykcs11_softhsm2/) image we created which installs Python, SoftHSM, and PyKSC11 from the master branch.

1. Setup SoftHSM with a PIN

```
softhsm2-util --init-token --slot 0 --label test --pin 1234
```

2. Execute `rsa_encrypt.py`

As a note, if we remove the `RSAOAEPMechanism` mechanism and instead rely on the default `MechanismRSAPKCS1`, it works just fine.

Any help would be greatly appreciated!

**Comment by LudovicRousseau** [comment]
SoftHSM2 does **NOT** support RSA OAEP SHA256 (CKM_SHA256).
The code now uses SHA1 instead (CKM_SHA_1)

Fixed in https://github.com/LudovicRousseau/PyKCS11/commit/b791bac1c57aba22ad68c54ba131fc3959e86d01

**Comment by jordan-wright** [comment]
Holy cow, that was fast. Thanks so much for the quick response!
