### ISSUE TITLE
C_Unwrap SIGTERM with Thales nShield 

### ISSUE THREAD

**Issue by maestrx** [LudovicRousseau/PyKCS11#18]
#### Your system information

* PyKCS11 version: PyKCS11-1.4.3
* Python version: python-2.7.5-58.el7.x86_64

#### Please describe your issue in as much detail as possible:
When doing C_Unwrap with 3DES key using handle (previously unwrapped in HSM) and DES2 key provided as input I get SIGTERM. When debuggin this issue with gdb I am getting this trace:

Program received signal SIGSEGV, Segmentation fault.
_[Switching to Thread 0x7fffee91d700 (LWP 8849)]
unwrap_secret (sess=0x7fffe8003240, realslot=0x7b40d0, wrappingkeyobjdata=0xa75aa641, pMechanism=0x7fffe800a650, mechdata=0x0, pWrappedKey=0xc <Address 0xc out of bounds>, ulWrappedKeyLen=16,
    pTemplate=0x7fffe800e2c0, ulAttributeCount=15, phKey=0x7fffee91be58) at ../keymanunwrap.c:614
614     ../keymanunwrap.c: No such file or directory._

I interpret it as if the python wrapper over the PKCS so library(LowLevel.so) would not be able to properly pass the pointer to the pWrappedKey, as the value passed (0xc) does not look like a valid pointer :)
#### Steps for reproducing this issue:

I can provide you with the python code I used, I  cannot provide you with Thales HSM's nor the Thales PKCS libraries. I'm willing to collaborate with debugging of this issue.

BTW: Thanks for this great project, I was looking to implement it using ctypes, but your code is saving plenty of headaches and time :) Great job done mate :)

Thanks
Vit

**Comment by maestrx** [comment]
More debugging info :) added some variable dumps in teh end of SWIGINTERN PyObject *_wrap_CPKCS11Lib_C_UnwrapKey(PyObject *SWIGUNUSEDPARM(self), PyObject *args) {

    outfile << obj3;
           outfile << "\n";

       outfile << arg1;
       outfile << arg2;
       outfile << arg3;
       outfile << arg4;
       outfile << arg7;

 in the src/pykcs11_wrap.cpp and getting this data:
0x7fb298f91d10
0x205a790
2251
0x7fb290002040
1125
0x7fb290000ce0



Wondering thy the

**Comment by LudovicRousseau** [comment]
Can you try to reproduce the problem using SoftHSM2 as the PKCS#11 library?
https://github.com/opendnssec/SoftHSMv2

The best would be to write a ``test/test_wrap.py`` script to add automatic test of the function.

**Comment by maestrx** [comment]
```
Ive downloaded and deployed the SoftHSM2 as you suggested. And the same code is raising this error:
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./oke2.py", line 93, in worker
    otakeyunwrapped = sess.unwrapKey(sessionkeyunwrapped, binascii.unhexlify(otakeywrapped), otakeytemplate, otakeymech)
  File "/usr/lib64/python2.7/site-packages/PyKCS11/__init__.py", line 1191, in unwrapKey
    raise PyKCS11Error(rv)
PyKCS11Error: CKR_MECHANISM_INVALID (0x00000070)

```

Relevant source code part is:
sessionkeyunwrapped is DES3 key previously unwrapped. 
otakeywrapped is a a RAW key value to be unwrapped with the session key

                    otakeytemplate = [(CKA_TOKEN, False), (CKA_KEY_TYPE, CKK_DES2), (CKA_LABEL, 'OTATemp.'+str(threading.current_thread().ident)),
                                      (CKA_PRIVATE, True), (CKA_SIGN, True), (CKA_VERIFY, True), (CKA_UNWRAP, True), (CKA_DERIVE, True),
                                      (CKA_CLASS, CKO_SECRET_KEY), (CKA_MODIFIABLE, True), (CKA_ENCRYPT, True), (CKA_DECRYPT, True),
                                      (CKA_EXTRACTABLE, True), (CKA_SENSITIVE, True), (CKA_WRAP, True)]
                    otakeymech = Mechanism(CKM_DES3_CBC, 0x0)
                    otakeyunwrapped = sess.unwrapKey(sessionkeyunwrapped, binascii.unhexlify(otakeywrapped), otakeytemplate, otakeymech)


```

The java code that works and I'm taking it as a refference is the mechanism defined this way: 

```
            mechanismUnwrap = CKConstants.CKM_DES3_CBC;
   	    byte[] paramUnWrap = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
            unwrapMechanism = new CKMechanism(mechanismUnwrap, paramUnWrap);

```

Thanks for any suggestiosn how to do the same in the python code... :)

**Comment by maestrx** [comment]
issue fixed, incorrectly defined initialization vector :) 
otakeymech = Mechanism(CKM_DES3_CBC, [0] * 8)
this line fixed it all :)

Thanks for support and for great project! :)

**Comment by LudovicRousseau** [comment]
So the problem was in your code. Exact?
