### ISSUE TITLE
X509 Certificate import issue/question

### ISSUE THREAD

**Issue by xzr** [LudovicRousseau/PyKCS11#21]
#### Your system information

* PyKCS11 version: 1.4.2
* Python version: 2.7.12

#### Please describe your issue in as much detail as possible:
Hi, I was following the example described in https://github.com/LudovicRousseau/PyKCS11/blob/master/samples/genkeypair_import_cert.py

I'm currently using SoftHSM2 for testing, but the end result will be running against a Safenet HSM. 

I've followed the steps in the example, created a certificate using pyca/cryptography and converting that with PyASN1. However it seems that the certificate doesn't get created on the token.

Key creation and signing the certificate with the key seems to work fine.

Is the certificate supposed to get stored on the token when the template is created?
Or maybe there's a function call I'm missing here?

**Comment by xzr** [comment]
Ah I reckon I should use session.createObject(tmpl), will give it a try

**Comment by LudovicRousseau** [comment]
Exact. The sample code is not complete.
I added the missing line in https://github.com/LudovicRousseau/PyKCS11/commit/44ebcb23d4ca36168b56b318f85a122da5182447
