### ISSUE TITLE
(py3) C_Login pin should accept bytes

### ISSUE THREAD

**Issue by mon** [LudovicRousseau/PyKCS11#22]
Python 3.6.1, Win32.
My dongle pin is derived from a hash and is thus binary. In python 3, none of the decoders I tried a) work without hitting invalid chars or b) provide the correct login pin to the Cryptoki library.

Attempting to pass bytes results in:
```    session.login(pin, CKU_USER)
  File "C:\Python36\lib\site-packages\PyKCS11\__init__.py", line 901, in login
    rv = self.lib.C_Login(self.session, user_type, pin)
  File "C:\Python36\lib\site-packages\PyKCS11\LowLevel.py", line 1789, in C_Login
    return _LowLevel.CPKCS11Lib_C_Login(self, hSession, userType, pPin)
TypeError: in method 'CPKCS11Lib_C_Login', argument 4 of type 'char *'
```
Note that this works fine in Python 2.

I'm not sure how to modify the declarations to treat `bytes` as a `char*`

**Comment by LudovicRousseau** [comment]
The ``C_Login()`` pin parameter is supposed to be a ``CK_UTF8CHAR_PTR`` at the PKCS#11 level.
Please provide the code you are using.

**Comment by mon** [comment]
```python
from PyKCS11 import *

pkcs11 = PyKCS11Lib()
pkcs11.load("dkck201")

pin = b'\xbf\xa7\x91\x19v\x07\x9fkuz2\xd6\x9b\xaaFq'

slot = pkcs11.getSlotList(True)[0]
session = pkcs11.openSession(slot, CKF_SERIAL_SESSION | CKF_RW_SESSION)
session.login(pin, CKU_USER)
print("Successful login)"
```

With Python 2, login is successful. With Python 3, I get the error as above. If I remove the `b` prefix from the string, the pin is incorrect (`CKR_PIN_INCORRECT`)

**Comment by LudovicRousseau** [comment]
In Python 2 strings and binary buffers are the same.
This is not true with Python 3.

Your PIN value is not a valid UTF-8 string (as requested by PKCS#11 specification):
```
>>> pin = b'\xbf\xa7\x91\x19v\x07\x9fkuz2\xd6\x9b\xaaGq'
>>> pin.decode("utf-8", "strict")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 0: invalid start byte
```
I think your Datakey Cryptoki "dkck201" library is not PKCS#11 compliant.

Maybe it is possible to change PyKCS11 accept any buffer at ``C_Login()`` without breaking existing code. I will have a look.
Patches are welcome :-)

**Comment by mon** [comment]
I would have submitted a patch but I do not know how to change the buffer type, apologies :)

I agree that it is not compliant, but vendors never pay attention to these things and leave me with technically invalid passwords :(

**Comment by LudovicRousseau** [comment]
Fixed in https://github.com/LudovicRousseau/PyKCS11/commit/6a179debb47a1cc7ac898bfb866735f8cf52f3b8
