### ISSUE TITLE
error when installing PykCS11 with pip on a win7 64bit

### ISSUE THREAD

**Issue by kazacube-hsmaiti** [LudovicRousseau/PyKCS11#24]
#### Your system information

* PyKCS11 version:1.4.4
* Python version:2.7

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.
I tried to install PyKsc11 on a windows7 64bit using pip
but i got this error: 
""""""""
**error c2039 'data' is not a member of std::vector with 
[
_Ty= unsigned char
]**
""""""""
i'm using python 2.7 with a Microsoft Visual C++ Compiler v9. 
#### Steps for reproducing this issue:

1. pip install Pykcs11

**Comment by LudovicRousseau** [comment]
Can you add the file and line number causing the error?

**Comment by kazacube-hsmaiti** [comment]
@LudovicRousseau 
here is the message i got when i try installing via pip:

![capture du 2017-11-07 12-41-31](https://user-images.githubusercontent.com/32460729/32494365-4b6b2c66-c3b9-11e7-807f-13b9ddcf1a7c.png)

**Comment by LudovicRousseau** [comment]
What is the line 15850 of the file ``src/pykcs11_wrap.cpp``?
Please provide 5 lines before and 5 lines after line 15850.

It looks like ``std::vector::data`` is available since C++11
http://en.cppreference.com/w/cpp/container/vector/data

Maybe your C++ compiler is too old, or not correctly configured.

**Comment by kazacube-hsmaiti** [comment]
@LudovicRousseau 

![capture du 2017-11-07 15-06-08](https://user-images.githubusercontent.com/32460729/32500403-3ccf31de-c3cd-11e7-94d2-ed854be8201c.png)

**Comment by LudovicRousseau** [comment]
I suggest you to upgrade your compiler.
Or check how to enable C++11 support.

**Comment by kazacube-hsmaiti** [comment]
well, i don't really get it because when installing PYKCS11, it demande to have visual C++ compiler 9.
I'll see what i can do, but please if you can just answer those questions.

Q1- What is the best way to install PYKCS11 on a windows x64 (**Python version,compiler,and other dependencies...**) ?

Q2- Can i for exemple use Mingw x64 for the installation instead of c++ compiler ?
PS:
i want to use the pykcs11 with other libraries as eventlet and pyOpenssl, wich can cause problems with version compatibility of python (2.7).

**Comment by LudovicRousseau** [comment]
I do not use Windows. I can't help you for that.

**Comment by m32** [comment]
diff -r ./src/pykcs11_wrap.cpp W:\projekty\python\pymodules\PyKCS11-1.4.3/src/pykcs11_wrap.cpp
15850c15850,15852
<       arg2 = vect->data();
---
>       // TODO m32
>       // arg2 = vect->data();
>       arg2 = &vect[0];

VC9 has some troubles with std namespace, this patch works for me in python 2.7

**Comment by LudovicRousseau** [comment]
I fixed a windows build issue in 93c0361ffc3056daf7e282627b16bbf7c547e877
Can you try again with the latest PyKCS11 version (1.5.2)?

**Comment by m32** [comment]
For me (python setup.py build) produces simple error, file not exists: src/LowLevel.py, since it's generated in toplevel directory, next fix is required:
copy_file("src/LowLevel.py", "PyKCS11")
copy_file("LowLevel.py", "PyKCS11")

**Comment by LudovicRousseau** [comment]
Do you know why ``LowLevel.py`` is not generated in ``src/`` in your case?

According to the AppVeyor results, the current PyKCS11 builds fine for 32/64 bits and different Python versions
https://ci.appveyor.com/project/LudovicRousseau/pykcs11

**Comment by m32** [comment]
My fault, I used a non-standard swig

**Comment by LudovicRousseau** [comment]
I think this bug is now fixed.
