### ISSUE TITLE
Problem invoking RSA_PSS_Mechanism()

### ISSUE THREAD

**Issue by esuzukiaws** [LudovicRousseau/PyKCS11#25]
#### Your system information

* PyKCS11 version: 1.4.4
* Python version: 3.4.3

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

I have created a script that signs data using the CKM_SHA*_RSA_PKCS_PSS mechanisms. Since these mechanisms require an structure to be configured, I'm configuring them using RSA_PSS_Mechanism like this:

```python
if (not args.mechanism) or (args.mechanism == "CKM_SHA1_RSA_PKCS_PSS"):`
    mecha = CKM_SHA1_RSA_PKCS_PSS`
    mecha_parameters = RSA_PSS_Mechanism(CKM_SHA_1, mgf=CKG_MGF1_SHA1, sLen=20)`
elif args.mechanism == "CKM_SHA224_RSA_PKCS_PSS":
    mecha = CKM_SHA224_RSA_PKCS_PSS
    mecha_parameters = RSA_PSS_Mechanism(CKM_SHA224, mgf=CKG_MGF1_SHA224, sLen=20)
elif args.mechanism == "CKM_SHA256_RSA_PKCS_PSS":
    mecha = CKM_SHA256_RSA_PKCS_PSS
    mecha_parameters = RSA_PSS_Mechanism(CKM_SHA256, mgf=CKG_MGF1_SHA256, sLen=20)
elif args.mechanism == "CKM_SHA384_RSA_PKCS_PSS":
    mecha = CKM_SHA384_RSA_PKCS_PSS
    mecha_parameters = RSA_PSS_Mechanism(CKM_SHA384, mgf=CKG_MGF1_SHA384, sLen=20)
elif args.mechanism == "CKM_SHA512_RSA_PKCS_PSS":
    mecha = CKM_SHA512_RSA_PKCS_PSS
    mecha_parameters = RSA_PSS_Mechanism(CKM_SHA512, mgf=CKG_MGF1_SHA512, sLen=20)
else:
    print("An invalid mechanism was specified. Aborting...")
    sys.exit(1)
```
Then, I effectively sign the data like this:

```python
signature = sess.sign(privateKey, data, Mechanism(mecha, mecha_parameters))
```

When I run the script, it gives me an error like this:

```
Traceback (most recent call last):
  File "./sign_data_using_RSA_PKCS_PSS_algorithms.py", line 113, in <module>
    signature = sess.sign(privateKey, data, Mechanism(mecha, mecha_parameters))
  File "/home/ec2-user/.local/lib/python3.4/site-packages/PyKCS11/__init__.py", line 723, in __init__
    self._param = ckbytelist(param)
  File "/home/ec2-user/.local/lib/python3.4/site-packages/PyKCS11/__init__.py", line 112, in __init__
    raise PyKCS11.PyKCS11Error(-3, text=type(data))
PyKCS11.PyKCS11Error: Unknown format (<class 'PyKCS11.RSA_PSS_Mechanism'>)
```

Am I doing anything wrong?

**Comment by LudovicRousseau** [comment]
I fixed the support of RSA PKCS PSS mechanism in https://github.com/LudovicRousseau/PyKCS11/commit/0ce351d4168936cb5bc04b8b854a9e5340e8d7ea
This fix is not yet included in a stable release.

Please test with the current git code and tell me if that fixes your problem.

**Comment by esuzukiaws** [comment]
Ludovic,

Thanks for the fast reply! I've tried with the new code and now the error is different:

```
C_Logout failed with error CKR_USER_NOT_LOGGED_IN : 0x00000101
Traceback (most recent call last):
  File "./sign_data_using_RSA_PKCS_PSS_algorithms.py", line 84, in <module>
    sess.login(credentials)  # CU username:password
  File "/home/ec2-user/.local/lib/python3.4/site-packages/PyKCS11/__init__.py", line 909, in login
    rv = self.lib.C_Login(self.session, user_type, pin1)
  File "/home/ec2-user/.local/lib/python3.4/site-packages/PyKCS11/LowLevel.py", line 1789, in C_Login
    return _LowLevel.CPKCS11Lib_C_Login(self, hSession, userType, pPin)
TypeError: in method 'CPKCS11Lib_C_Login', argument 4 of type 'char *'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./sign_data_using_RSA_PKCS_PSS_algorithms.py", line 129, in <module>
    sess.logout()
  File "/home/ec2-user/.local/lib/python3.4/site-packages/PyKCS11/__init__.py", line 919, in logout
    raise PyKCS11Error(rv)
PyKCS11.PyKCS11Error: CKR_USER_NOT_LOGGED_IN (0x00000101)
```

In my case, I'm using an HSM from Cavium, so this is the way I log in to the session:

```python
sess = pkcs11.openSession(slot, CKF_SERIAL_SESSION | CKF_RW_SESSION)
credentials = user + ":" + passwd
sess.login(credentials)
```

**Comment by LudovicRousseau** [comment]
I have changed the way the PIN code is used.
Please try to login to your HSM using a simple code.

**Comment by esuzukiaws** [comment]
Ludovic,

I've tried to specify a simple code when logging into the HSM, however it's not accepting it. I've tried authenticating using only the password of a crypto-user, but then I get the same error as above.

After browsing through the Cavium documentation, I've found out that it really requires a PIN specified as <crypto-user>:<password>. It's different from SafeNet HSMs, which accept simple-code PINs.

So, now I'm stuck, not being able to authenticate the HSM session. Do you have any ideas on how to solve this issue?

**Comment by LudovicRousseau** [comment]
Please use ``pkcs11-spy.so`` library from OpenSC https://github.com/OpenSC/OpenSC/releases to get a log of the PKCS#11 calls.
I need to know exactly what data has been sent to your Cavium HSM in the ``C_Login()`` function.

You can also try the sample code https://github.com/LudovicRousseau/PyKCS11/blob/master/samples/getinfo.py

**Comment by LudovicRousseau** [comment]
I can't help if you do not provide more details.
Closing the issue.
