### ISSUE TITLE
Session.sign will fill the memory and cause a SIGABRT when data argument is a very big integer

### ISSUE THREAD

**Issue by gonccalo** [LudovicRousseau/PyKCS11#26]
#### Your system information

* PyKCS11 version: 1.4.4
* Python version: 3.6.4

#### Please describe your issue in as much detail as possible:
When calling the `session.sign(key, data)` function if the `data` argument is a integer then a `ckbytelist` will be created using `ckbytelist(data)` [[1]](https://github.com/LudovicRousseau/PyKCS11/blob/f332518d4f61ba301e39e4ecc03d6ba5ca0f8410/PyKCS11/__init__.py#L1039), this will create a `ckbytelist` of size `data`[[2]](https://github.com/LudovicRousseau/PyKCS11/blob/f332518d4f61ba301e39e4ecc03d6ba5ca0f8410/PyKCS11/__init__.py#L77) so if `data` is a very big number the process will crash with 
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```
#### Steps for reproducing this issue:

I can reproduce the error with
```python
import PyKCS11
if __name__ == '__main__':
    bignum = 24401231876787445786723
    print(bignum.bit_length())
    pk = PyKCS11.PyKCS11Lib()
    pk.load("libpteidpkcs11.so")
    slots = pk.getSlotList()
    if len(slots) < 1:
        exit()
    session = pk.openSession(slots[0])
    key = session.findObjects(template=((PyKCS11.CKA_LABEL, "CITIZEN AUTHENTICATION KEY"),
                                             (PyKCS11.CKA_CLASS, PyKCS11.CKO_PRIVATE_KEY),
                                             (PyKCS11.CKA_KEY_TYPE, PyKCS11.CKK_RSA)))[0]
    mec = PyKCS11.Mechanism(PyKCS11.CKM_SHA1_RSA_PKCS, "")
    signed = session.sign(key, bignum, mec)
    print(signed)
```
 
To fix this maybe you can check if `data` is a integer in the sign function and convert it to a byte array or just throw an exception.

**Comment by LudovicRousseau** [comment]
Exact.
I will try to find a smart solution to detect the problem.

I don't really know how to "'convert an integer into a byte array". The application should know best what to do. Raising an exception should be the best solution.

**Comment by gonccalo** [comment]
Thanks.
There are other functions were this also happens, like [setPin()](https://github.com/LudovicRousseau/PyKCS11/blob/f332518d4f61ba301e39e4ecc03d6ba5ca0f8410/PyKCS11/__init__.py#L941) for example.
I think you can convert a int to byte array with `number.to_bytes((number.bit_length() + 7) // 8, 'big')`

**Comment by LudovicRousseau** [comment]
Fixed in https://github.com/LudovicRousseau/PyKCS11/commit/68da72764629c9197b091274fb9531b08b9ecf00

I added a test for your specific use case in https://github.com/LudovicRousseau/PyKCS11/commit/d72ff3e6bd48f69459506b842c925ed3ccd129af
