### ISSUE TITLE
initPin is not working, typo

### ISSUE THREAD

**Issue by fzonneveld** [LudovicRousseau/PyKCS11#33]
#### Your system information

* PyKCS11 version: 1.5.1
* Python version: 3.5.2

#### Please describe your issue in as much detail as possible:
initPin uses pin method parameter, not present.

**Comment by LudovicRousseau** [comment]
Fixed in https://github.com/LudovicRousseau/PyKCS11/commit/3345cab25670618bf32695ac88ba96cd0d9b019c
Thanks

**Comment by fzonneveld** [comment]
Thanks for the quick response


Op wo 11 apr. 2018 15:35 schreef Ludovic Rousseau <notifications@github.com
