### ISSUE TITLE
Error compiling in Ubuntu 16.04

### ISSUE THREAD

**Issue by evandrojr** [LudovicRousseau/PyKCS11#35]
#### Your system information

* PyKCS11 version: latestest
* Python version: 3.5

#### Please describe your issue in as much detail as possible:
Should compile PkKCS11, error:

% make build     
python setup.py build
running build
running build_ext
building 'PyKCS11._LowLevel' extension
swigging src/pykcs11.i to src/pykcs11_wrap.cpp
swig -python -c++ -o src/pykcs11_wrap.cpp src/pykcs11.i
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/local/include -I/usr/include/python2.7 -c src/ck_attribute_smart.cpp -o build/temp.linux-x86_64-2.7/src/ck_attribute_smart.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/local/include -I/usr/include/python2.7 -c src/pkcs11lib.cpp -o build/temp.linux-x86_64-2.7/src/pkcs11lib.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/local/include -I/usr/include/python2.7 -c src/pykcs11string.cpp -o build/temp.linux-x86_64-2.7/src/pykcs11string.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/local/include -I/usr/include/python2.7 -c src/utility.cpp -o build/temp.linux-x86_64-2.7/src/utility.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/local/include -I/usr/include/python2.7 -c src/pykcs11_wrap.cpp -o build/temp.linux-x86_64-2.7/src/pykcs11_wrap.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
src/pykcs11_wrap.cpp:171:21: fatal error: Python.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Makefile:12: recipe for target 'build-stamp' failed
make: *** [build-stamp] Error 1

#### Steps for reproducing this issue:

1. Download master PyKCS11 from github
2. Run: make build

**Comment by LudovicRousseau** [comment]
Install the package libpython3.5-dev

You can also use (or backport) the python3-pykcs11 package instead of rebuilding PyKCS11 yourself.
