### ISSUE TITLE
PyKCS11.PyKCS11Error: CKR_OBJECT_HANDLE_INVALID

### ISSUE THREAD

**Issue by spike-spb** [LudovicRousseau/PyKCS11#36]
#### Your system information

* PyKCS11 version: 1.4.4
* Python version: 2.7

#### Please describe your issue in as much detail as possible:
Hello!
I am trying to sign "hello world" with the following code (based on https://github.com/LudovicRousseau/PyKCS11/blob/master/samples/signature.py)
```
keyID = (49,)
private_keys = hSession.findObjects([
     (PyKCS11.CKA_CLASS, PyKCS11.CKO_PRIVATE_KEY),
     (PyKCS11.CKA_ID, keyID)
])
priv_key = private_keys[0]
mech = PyKCS11.Mechanism(PyKCS11.CKM_GOSTR3410, None)
to_sign = '48656c6c6f20776f726c640d0a'
signed_data = session.sign(priv_key, binascii.unhexlify(to_sign), mech)
```

This gives me:
`PyKCS11.PyKCS11Error: CKR_OBJECT_HANDLE_INVALID (0x00000082)`

If I change mech to `PyKCS11.Mechanism(PyKCS11.CKM_SHA1_RSA_PKCS, None)` then I get:
`PyKCS11.PyKCS11Error: CKR_KEY_TYPE_INCONSISTENT (0x00000063)`

Is it a problem with private key?

**Comment by LudovicRousseau** [comment]
Please provide the **full source code** and the **full error message** so I have the line numbers.

**Comment by spike-spb** [comment]
Here:
https://pastebin.com/WqEw3cQw

I am using USB token (like this one: https://www.aladdin-rd.ru/catalog/jacarta-gost/index), they say it supports GOST R3410.

The program gives an error:
```
Traceback (most recent call last):                                                                                                                                                            
  File "./signature.py", line 44, in <module>                                                                                                                                                 
    signature = session.sign(privKey, binascii.unhexlify(toSign), mech)                                                                                                                       
  File "/home/spike/.local/lib/python2.7/site-packages/PyKCS11/__init__.py", line 1048, in sign                                                                                             
    raise PyKCS11Error(rv)                                                                                                                                                                    
PyKCS11.PyKCS11Error: CKR_OBJECT_HANDLE_INVALID (0x00000082)                                                                                                                                  
```
Also I use special pkcs11 library from Alladin (that comes with JaCarta GOST SDK).
Program can login, can find the key, can find certificates and other objects, but can't sign with GOST R3410.

**Comment by spike-spb** [comment]
print(privKey) shows:
```
CKA_ALWAYS_SENSITIVE: True
CKA_CLASS: CKO_PRIVATE_KEY
CKA_END_DATE: ()
CKA_EXTRACTABLE: (0L,)
CKA_GOSTR3410_PARAMS: (6L, 7L, 42L, 133L, 3L, 2L, 2L, 35L, 1L)
CKA_GOSTR3411_PARAMS: (6L, 7L, 42L, 133L, 3L, 2L, 2L, 30L, 1L)
CKA_ID: ()
CKA_KEY_TYPE: CKK_GOSTR3410
CKA_LABEL: Private key
CKA_LOCAL: True
CKA_MODIFIABLE: False
CKA_NEVER_EXTRACTABLE: True
CKA_PRIVATE: True
CKA_SENSITIVE: True
CKA_SIGN: True
CKA_START_DATE: ()
CKA_SUBJECT: ()
CKA_TOKEN: True
CKA_UNWRAP: False
CKA_VALUE_LEN: 0
```

**Comment by LudovicRousseau** [comment]
It is the ``C_Sign()`` call at the PKCS#11 level that reports the error.

I never used GOST before so I don't know how to use this algorithm.
I was able to use ``sign()`` with ``PyKCS11.Mechanism(PyKCS11.CKM_GOSTR3410_WITH_GOSTR3411, None)`` (see https://github.com/LudovicRousseau/PyKCS11/blob/master/tests/test_asymetric_gost.py#L67) but not with ``PyKCS11.Mechanism(PyKCS11.CKM_GOSTR3410, None)`` as in your sample.

**Comment by LudovicRousseau** [comment]
According to http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/cs01/pkcs11-curr-v2.40-cs01.html#_Toc399399139 the use of CKM_GOSTR3410 is for "Single-part operations only". I have no idea what that means.

**Comment by spike-spb** [comment]
"C_SignUpdate continues a multiple-part signature operation, processing another data part."
see https://www.cryptsoft.com/pkcs11doc/v230/ in
Cryptographic Token Interface Standard/Functions/Signing and MACing functions

**Comment by LudovicRousseau** [comment]
I see.
PyKCS11 `.sign()` uses `C_Sign()` and not `C_SignUpdate()`/`C_SignFinal()`.

Since I was able to use `sign()` with `PyKCS11.Mechanism(PyKCS11.CKM_GOSTR3410_WITH_GOSTR3411, None)` in my sample code I don't know why it fails for you. Maybe you should report the problem to your PKCS#11 library provider.

**Comment by LudovicRousseau** [comment]
It looks like a bug in the PKCS#11 library used, not in PyKCS11.
