### ISSUE TITLE
PyKCS11 with Aladdin R.D. tokens

### ISSUE THREAD

**Issue by Goblenus** [LudovicRousseau/PyKCS11#39]
#### System information

* Operating system used: Windows 10 Pro 10.0.17134
* PyKCS11 version: 1.5.2
* Python version: 3.7.0
* PKCS#11 library used: jcPKCS11-2.dll (Aladdin R.D.)

#### Details:
Hello

I want to use PyKCS11 with [JaCarta PKI/ГОСТ](https://www.aladdin-rd.ru/catalog/jacarta-pki-gost/index). But they has some specific methods in their PKCS#11 such as `JC_PKI_SetComplexity`. How can I invoke them using PyKCS11.

**Comment by Goblenus** [comment]
Ok, this in not a problem to add it. Is there any details, that I should know?

**Comment by LudovicRousseau** [comment]
Read the source code.
Keep in mind that PyKCS11 is using the GNU GPL v2 license.

Good luck.
