### ISSUE TITLE
Can't run sample scripts using the LowLevel library

### ISSUE THREAD

**Issue by ohadm2** [LudovicRousseau/PyKCS11#40]
################## My system information ###############

* Operating system used: Windows 10 (build 1803)
* PyKCS11 version: 1.5.2
* Python version: 3.7
* PKCS#11 library used: PyKCS11.LowLevel

###################################################

Hi. 

First of all, I want to say thank you for that great module!

As for my problem, I am simply trying to run one of your LowLevel sample scripts (test.py in particular) and I fail.

The error message is related to UTF-8 encoding problem.

After doing further investigation it seems like the problem resides in the call to the function "GetLabel".

Please see the attached picture for more details (note that I'm using Athena's driver to access the smartcard).

Can you please help me figure out this problem?

Thanks!

![decode-err](https://user-images.githubusercontent.com/13061670/46717264-f3e35c00-cc6f-11e8-9da2-4c97a16e009d.PNG)

**Comment by LudovicRousseau** [comment]
Can you try again using the latest (unreleased) version?
You can get Windows binaries from https://ci.appveyor.com/project/LudovicRousseau/pykcs11

I fixed a UTF-8 issue in https://github.com/LudovicRousseau/PyKCS11/commit/84b921bc74b2416c977b852fe430ea9649342e04

**Comment by ohadm2** [comment]
Thanks for replying.

 That sounds great, but I can't find any binaries in the link you've sent me.

Can you please send me a DIRECT link? or an explanation?

**Comment by LudovicRousseau** [comment]
https://github.com/LudovicRousseau/PyKCS11#windows-binaries

**Comment by ohadm2** [comment]
The new link takes me to the link above and there is nothing there.

Please see the attached picture.
![no-bin](https://user-images.githubusercontent.com/13061670/46783098-ad563600-cd31-11e8-8c20-97281bdd585f.PNG)

**Comment by LudovicRousseau** [comment]
You need to select the Python version you use.

**Comment by ohadm2** [comment]
Oh...Now I get it. Thanks.

It confused me because the options are ENV var defs...
Anyway, I ran the sample script again using the latest version as you suggested but now I get a different error.

Picture attached.

![type-err](https://user-images.githubusercontent.com/13061670/46803398-b0204d80-cd68-11e8-99a9-64d592a66772.PNG)

**Comment by LudovicRousseau** [comment]
I understand your problem.
The samples in `samples/LowLevel/` are _no more_ functional since I changed the way the PIN is managed internally.
To make your code work you need to use a method from the high level API. For example I fixed the `test.py` sample using this patch:
```patch
diff --git a/samples/LowLevel/test.py b/samples/LowLevel/test.py
index c06c3e7..68ada76 100755
--- a/samples/LowLevel/test.py
+++ b/samples/LowLevel/test.py
@@ -20,6 +20,7 @@ from __future__ import print_function
 
 import PyKCS11.LowLevel
 import os
+from PyKCS11 import ckbytelist
 
 a = PyKCS11.LowLevel.CPKCS11Lib()
 info = PyKCS11.LowLevel.CK_INFO()
@@ -31,7 +32,7 @@ session = PyKCS11.LowLevel.CK_SESSION_HANDLE()
 sessionInfo = PyKCS11.LowLevel.CK_SESSION_INFO()
 tokenInfo = PyKCS11.LowLevel.CK_TOKEN_INFO()
 slotList = PyKCS11.LowLevel.ckintlist()
-pin = "12345678"
+pin = ckbytelist("123456")
 
 print("Load of " + lib + ": " + str(a.Load(lib)))
 print("C_GetInfo: " + hex(a.C_GetInfo(info)))
```

I have not used the low level API directly since ages.
I will try to find a clever way to solve the problem.

**Comment by LudovicRousseau** [comment]
I fixed the LowLevel API sample codes to use `ckbytelist()`

Maybe you should use the high level API. It is much simpler to use.
