### ISSUE TITLE
Elliptic curve key creation

### ISSUE THREAD

**Issue by xzr** [LudovicRousseau/PyKCS11#43]
#### Your system information

* Operating system used: Ubuntu 18.04 x64
* PyKCS11 version: 1.4.2
* Python version: Python 2.7.15rc1
* PKCS#11 library used: /usr/lib/softhsm/libsofthsm2.so

#### Please describe your issue in as much detail as possible:
Hey,

I'm implementing ECDSA key support for an application that uses PyKCS11 to hook into a HSM. 

Looking into the example code, I couldn't find a mention about EC key creation.

Going through the PKCS#11 docs, I think I can figure out how to get a key created, but won't be too pythonic. (Particular painpoint being defining the CKA_EC_PARAMS, curve etc).

So I guess this breaks down to 2 points:
1. Am I just not finding some example or utility function to ease the process a bit or do those not exist?
2. EC examples would be very helpful 

I'll continue with my implementation and can probably contribute an example if none exists currently, but just wanted to get a discussion going about it.

Also, thanks for the great work on the library. It has made my life a lot easier :)

**Comment by LudovicRousseau** [comment]
Exact, I do not have any sample using ECC.
It is a very good idea to provide ECC samples using SoftHSM. Please make a Pull Request when you are ready.

**Comment by xzr** [comment]
https://github.com/LudovicRousseau/PyKCS11/pull/48

I might add more samples later. The downside of this one is that it requires asn1crypto as pykcs11 itself has no utility functions for handling the ec_params.

**Comment by LudovicRousseau** [comment]
Please continue your nice work on https://github.com/LudovicRousseau/PyKCS11/pull/48
