### ISSUE TITLE
CKR_TOKEN_NOT_PRESENT

### ISSUE THREAD

**Issue by edsonitk** [LudovicRousseau/PyKCS11#44]
windows 7
PyKCS11 1.5.3
Python 2.7.10
PYKCS11LIB==aetpkss1.dll

Error executing the following code:

from PyKCS11 import *
pkcs11 = PyKCS11Lib()
pkcs11.load()
slot = pkcs11.getSlotList(tokenPresent=True)[0]

session = pkcs11.openSession(slot, PyKCS11.CKF_RW_SESSION)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\PyKCS11\__init__.py", line 627, in openSes
sion
    raise PyKCS11Error(rv)
PyKCS11.PyKCS11Error: CKR_TOKEN_NOT_RECOGNIZED (0x000000E1)
>>> session = pkcs11.openSession(52482, PyKCS11.CKF_RW_SESSION)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\PyKCS11\__init__.py", line 627, in openSes
sion
    raise PyKCS11Error(rv)
PyKCS11.PyKCS11Error: CKR_TOKEN_NOT_PRESENT (0x000000E0)

Note: Certificate validated on some sites

**Comment by LudovicRousseau** [comment]
It is not an error in PyKCS11.
Your token (smart card) is not recognized by your PKCS#11 library (aetpkss1.dll). Just use the correct PKCS#11 library for your smart card/token.

**Comment by edsonitk** [comment]
Instead of using the reader driver, would it be possible to directly access the windows repository?

**Comment by LudovicRousseau** [comment]
I don't know.
