### ISSUE TITLE
CKA_UNWRAP_TEMPLATE

### ISSUE THREAD

**Issue by alfredgamulo** [LudovicRousseau/PyKCS11#45]
* PyKCS11 version: 1.5.3
* Python version: 3.6.7

I'm trying to create an RSA keypair with an UNWRAP_TEMPLATE. I was wondering if you can provide an example? I am getting an error on trying to create it, code pasted below:

```
    rsa_mechanism = Mechanism(CKM_RSA_X9_31_KEY_PAIR_GEN, None)
    CKA_UNWRAP_TEMPLATE = 1073742354
    unwrap_template = ((CKA_EXTRACTABLE, CK_FALSE),)
    public_label = "RSA_public_key"
    public_template = [
        (CKA_CLASS, CKO_PUBLIC_KEY),
        (CKA_TOKEN, CK_TRUE),
        (CKA_MODULUS_BITS, 2048),
        (CKA_PUBLIC_EXPONENT, (0x01, 0x00, 0x01)),
        (CKA_ENCRYPT, CK_TRUE),
        (CKA_VERIFY, CK_TRUE),
        (CKA_VERIFY_RECOVER, CK_TRUE),
        (CKA_WRAP, CK_TRUE),
        (CKA_LABEL, public_label)
    ]
    private_label = "RSA_private_key"
    private_template = [
        (CKA_TOKEN, CK_TRUE),
        (CKA_DECRYPT, CK_TRUE),
        (CKA_SIGN, CK_TRUE),
        (CKA_SIGN_RECOVER, CK_TRUE),
        (CKA_UNWRAP, CK_TRUE),
        (CKA_UNWRAP_TEMPLATE, unwrap_template),
        (CKA_LABEL, private_label)
    ]
    pub_key, pri_key = pkcs11.generate_key_pair(rsa_mechanism, public_template, private_template)
```
The error I'm seeing as follows:
```
self = <PyKCS11.LowLevel.CK_ATTRIBUTE_SMART; proxy of <Swig Object of type 'vector< CK_ATTRIBUTE_SMART >::value_type *' at 0x7facac2baed0> >
args = (1073742354, ((354, 0),))

>   def SetBin(self, *args): return _LowLevel.CK_ATTRIBUTE_SMART_SetBin(self, *args)
E   TypeError: in method 'CK_ATTRIBUTE_SMART_SetBin', argument 3 of type 'std::vector< unsigned char > const &'

/usr/local/lib64/python3.6/site-packages/PyKCS11/LowLevel.py:1365: TypeError
```

**Comment by LudovicRousseau** [comment]
I never used `CKA_UNWRAP_TEMPLATE` so I am not surprised it does not work.

I just pushed a change to define `CKA_UNWRAP_TEMPLATE` https://github.com/LudovicRousseau/PyKCS11/commit/2874b6caeafb76d8cff6910585ceb4ff7cfae059 so you do not have to do it in your code.

But support is not yet present. A patch would be welcome.
What is `generate_key_pair()`? Can you provide the full source code of your sample?

**Comment by alfredgamulo** [comment]
generate_key_pair was just an wrapper function so that I can log an exception:
```
def generate_key_pair(self, mechanism, public_template, private_template):
        try:
            return self.session.generateKeyPair(public_template, private_template, mecha=mechanism)
        except PyKCS11Error as e:
            logger.exception("Error encountered generating key pair\ne: {} \nmechanism: {} \npublic_template: {}\nprivate_template: {}".format(e, mechanism, public_template, private_template))
            raise
```

**Comment by alfredgamulo** [comment]
Essentially, what I'd like help with is to understand the syntax necessary to embed the nested template "CKA_UNWRAP_TEMPLATE" within the private key template.

**Comment by LudovicRousseau** [comment]
I think you can't do that. Code is missing in PyKCS11 to support `CKA_UNWRAP_TEMPLATE`.
My first guess would be to add support of array in `_template2ckattrlist()` https://github.com/LudovicRousseau/PyKCS11/blob/master/PyKCS11/__init__.py#L1297

I am not sure you can use `CKA_UNWRAP_TEMPLATE` with `.generateKeyPair()`. If I understand PKCS#11 v2.40 correctly it should be used with `C_UnwrapKey()`.

It looks like SoftHSMv2 does support `CKA_UNWRAP_TEMPLATE` so this can be used to test a sample code. https://github.com/opendnssec/SoftHSMv2/blob/develop/src/lib/SoftHSM.cpp#L6653
And it is used for `C_UnwrapKey()`.

**Comment by alfredgamulo** [comment]
It get's a little confusing, but as far as I understand, there are two templates that are in play during an unwrap key. My source is this: https://www.cryptsoft.com/pkcs11doc/v220/pkcs11__all_8h.html#aC_UnwrapKey

> To partition the unwrapping keys so they can only unwrap a subset of keys the attribute CKA_UNWRAP_TEMPLATE can be used on the unwrapping key to specify an attribute set that will be added to attributes of the key to be unwrapped. If the attributes do not conflict with the user supplied attribute template, in 'pTemplate', then the unwrap will proceed. The value of this attribute is an attribute template and the size is the number of items in the template times the size of CK_ATTRIBUTE. If this attribute is not present on the unwrapping key then no additional attributes will be added. If any attribute conflict occurs on an attempt to unwrap a key then the function shall return CKR_TEMPLATE_INCONSISTENT. 

The C_UnwrapKey takes the pTemplate parameter and applies the template to the unwrapped key.
However, the unwrapping key (the RSA private key) can also have a CKA_UNWRAP_TEMPLATE that applies a default template when the pTemplate is not supplied.

**Comment by LudovicRousseau** [comment]
What I propose you is you write a C-sample code using softHSMv2 and the PKCS#11 API to test the feature. The idea is to be sure to understand how it works.

Then I will try to modify PyKCS11 to add support and use your sample code converted to Python+PyKCS11 to test the implementation.

**Comment by alfredgamulo** [comment]
Hi @LudovicRousseau, I just wanted to give you a short update.
I'm wrestling with providing a working example for you.
What I have so far: https://gist.github.com/alfredgamulo/b6f605d00f148a5d739086dd972e2ecf
This works on CloudHSM. 
I am having issues with SoftHSMv2 where the wrap key function returns CKR_WRAPPED_KEY_LEN_RANGE. However, the RSA keys do generate with the CKA_UNWRAP_TEMPLATE in the CK_ATTRIBUTE list for the private key.

**Comment by LudovicRousseau** [comment]
Nice start.
The use of SoftHSMv2 is nearly mandatory to have working Unitary Tests. Maybe you can ask for help from SoftHSM project?

**Comment by alfredgamulo** [comment]
I was able to get my [gist](https://gist.github.com/alfredgamulo/b6f605d00f148a5d739086dd972e2ecf) to work in SoftHSMv2.

For anyone tracking the issue, my conversation with SoftHSMv2 [here](https://github.com/opendnssec/SoftHSMv2/issues/441).

**Comment by LudovicRousseau** [comment]
I can use your C sample code. Thanks. It will help.
I now need time and motivation to update PyKCS11.

**Comment by LudovicRousseau** [comment]
I am working on it.
It is more complex than expected.

**Comment by LudovicRousseau** [comment]
I implemented a solution in https://github.com/LudovicRousseau/PyKCS11-debug
A sample code is available at https://github.com/LudovicRousseau/PyKCS11-debug/blob/master/test/test_wrap.py#L211

Please use the PyKCS11-debug project and confirm if it works for you so I can include it in the official PyKCS11.
Thanks.

**Comment by alfredgamulo** [comment]
LGTM, thank you so much

**Comment by LudovicRousseau** [comment]
Added in PyKCS11 version 1.5.4 released yesterday.
