### ISSUE TITLE
Support for CK_GCM_PARAMS

### ISSUE THREAD

**Issue by someshi** [LudovicRousseau/PyKCS11#49]
The .i file includes CKM_AES_GCM but not the corresponding CK_GCM_PARAMS structure to use the GCM mechanism.

Sample code using CK_GCM_PARAMS
https://github.com/aws-samples/aws-cloudhsm-pkcs11-examples/blob/481f533cc61f0aa4deee42712746932e508b243b/src/encrypt/gcm.c

**Comment by LudovicRousseau** [comment]
Can you propose a patch and a Unitary Test code?

**Comment by LudovicRousseau** [comment]
I added a preliminary support in https://github.com/LudovicRousseau/PyKCS11-debug/tree/devel

But I get the error `CKR_MECHANISM_INVALID` if I use SoftHSM https://github.com/opendnssec/SoftHSMv2 to test my code
```
27: C_EncryptInit
2019-04-18 15:39:20.240
[in] hSession = 0x1
pMechanism->type=CKM_AES_GCM                  
[in] pIv[ulIvLen] 00007fb557c10420 / 12
    00000000  2A 2A 2A 2A 2A 2A 2A 2A 2A 2A 2A 2A              ************    
[in] pAAD[ulAADLen] 00007fb557c47950 / 13
    00000000  70 6C 61 69 6E 74 65 78 74 20 61 61 64           plaintext aad   
pMechanism->pParameter->ulTagBits=16
[in] hKey = 0x2
Returned:  112 CKR_MECHANISM_INVALID
```

Could you provide a working sample code in C using SoftHSM?

**Comment by LudovicRousseau** [comment]
Added in https://github.com/LudovicRousseau/PyKCS11/commit/aceec8260e8ffb992e33526d376d3fd25f6e056c
