### ISSUE TITLE
Error installing PyKCS11 with pip install

### ISSUE THREAD

**Issue by kalyank23** [LudovicRousseau/PyKCS11#51]
#### Your system information

* Operating system used:
* PyKCS11 version: 1.5.3
* Python version: 2.7.16
* PKCS#11 library used: Not applicable

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen.
PyKCS11 would have installed successfully with pip install

Describe what _did_ happen.
Getting error as:

src/pykcs11_wrap.cpp(13610) : error C2065: 'SWIGTYPE_p_std__vectorT_unsigned_char_std__allocatorT_unsigned_char_t_t' : undeclared identifier

#### Steps for reproducing this issue:

1.  Install https://www.microsoft.com/en-us/download/confirmation.aspx?id=44266
2. And then run pip install PyKCS11

**Comment by LudovicRousseau** [comment]
I guess your "Operating system" is Windows. What version exactly?

**Comment by kalyank23** [comment]
It is 64 bit Windows 10 enterprise edition with swigwin 1.3.33 version

**Comment by kalyank23** [comment]
Sorry I installed 1.3.33 swig version for another python package and continued to use it with this version of PyKCS11 also. After installing latest SWIG 3.0.12 version, it installed successfully. Thanks.
