### ISSUE TITLE
CKR_MECHANISM_INVALID when use wrapKey

### ISSUE THREAD

**Issue by MasterMeng** [LudovicRousseau/PyKCS11#53]
* Operating system used: Ubuntu18.04
* PyKCS11 version: 1.5.3
* Python version: 3.7.2
When I used the func:wrapKey to wrap a key with CKM_DES3_CBC_PAD, I got the error: CKR_MECHANISM_INVALID
I also used CKM_DES3_ECB CKM_AES_CBC, they returned the same error: CKR_MECHANISM_INVALID

**Comment by LudovicRousseau** [comment]
This error is reported by the PKCS#11 library you use. You "forgot" to enter the information for "PKCS#11 library used:"
It is not a problem in PyKCS11.

**Comment by MasterMeng** [comment]
Thank you for your answer. Thanks God! That`s not my fault
