### ISSUE TITLE
HMAC general error

### ISSUE THREAD

**Issue by MasterMeng** [LudovicRousseau/PyKCS11#54]
* Operating system used: ubuntu 18.04
* PyKCS11 version: 1.5.3
* Python version: python3.7.2
* PKCS#11 library used: opencryptoki 3.11 --- soft token

In my project,I need to use hmac to sign some thing.So I use PyKCS11 to general a hmac key,like this:
hmacTem = [
    (CKA_CLASS, CKO_SECRET_KEY),
    (CKA_KEY_TYPE, CKK_AES),
    (CKA_TOKEN, CK_TRUE),
    (CKA_PRIVATE, CK_FALSE),
    (CKA_SIGN, CK_FALSE),
    (CKA_VERIFY, CK_FALSE),
    (CKA_VALUE_LEN, 32),
    (CKA_LABEL, "TestAESKey"),
]

hmac = session.generateKey(hmacTem, Mechanism(CKM_SHA256_HMAC, None))

Then I got this error:PyKCS11.PyKCS11Error: CKR_MECHANISM_INVALID (0x00000070)

Can I tell me where I`m wrong?

**Comment by LudovicRousseau** [comment]
I don't know what is wrong with your code.
It is not a PyKCS11 issue. You should learn how to use the PKCS#11 API first.
