### ISSUE TITLE
Library loading fails with Python 3.6 + Django 2.2.1

### ISSUE THREAD

**Issue by xzr** [LudovicRousseau/PyKCS11#57]
#### Your system information

* Operating system used: Ubuntu 18.04 x64
* PyKCS11 version: 1.5.3
* Python version: 3.6.7
* PKCS#11 library used: /usr/lib/softhsm/libsofthsm2.so

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen.
Library loads

Describe what _did_ happen.
Library fails to load with:

  File "/home/xzr/code/app/venv/lib/python3.6/site-packages/PyKCS11/__init__.py", line 483, in load
    raise PyKCS11Error(-1, pkcs11dll_filename)

This might be a PEBCAK issue, but so far I haven't been able to figure out what's wrong. I did play around with different input types for the library path string (and finally landed on lib_path.encode('ascii', 'ignore').decode('ascii') which in my opinion should produce the right kind of input for the underlying lowlevel library.

Not expecting a straight answer or anything. Mostly welcoming any ideas for debug. The error from the lowlevel parts is not particularly helpful.

The library loading seems to work fine if I cut django out of the equation.

**Comment by LudovicRousseau** [comment]
You should get a stack dump generated by the exception. No?

**Comment by xzr** [comment]
Yeah, File "/home/xzr/code/app/venv/lib/python3.6/site-packages/PyKCS11/init.py", line 483, in load
raise PyKCS11Error(-1, pkcs11dll_filename) is the last line. It looks like it does pass the string down to the lowlevel parts, but just plain fails to load up the .so (For unknown reasons). 

I'll try to investigate further

**Comment by LudovicRousseau** [comment]
Please copy/paste the full output.

**Comment by xzr** [comment]
> 
> Internal Server Error: /api/csr_sign
> Traceback (most recent call last):
>   File "/home/xzr/code/csr_api/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
>     response = get_response(request)
>   File "/home/xzr/code/csr_api/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/home/xzr/code/csr_api/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/home/xzr/code/csr_api/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/home/xzr/code/csr_api/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
>     return handler(request, *args, **kwargs)
>   File "/home/xzr/code/csr_api/site_csr/api/views.py", line 25, in post
>     out = csr_handler(csr)
>   File "/home/xzr/code/csr_api/site_csr/api/handlers/csr_handler.py", line 11, in csr_handler
>     crt = sign_csr_der('test_api1', csr, 'sha512')
>   File "/home/xzr/code/csr_api/site_csr/api/hsm_tool/hsm_tool.py", line 89, in sign_csr_der
>     hsm = _init_hsm()
>   File "/home/xzr/code/csr_api/site_csr/api/hsm_tool/hsm_tool.py", line 46, in _init_hsm
>     hsm = HSM(hsm_lib, hsm_pass, hsm_slot)
>   File "/home/xzr/code/csr_api/site_csr/api/hsm_tool/hsm/hsm.py", line 310, in __init__
>     self.lib.load(lib_p)
>   File "/home/xzr/code/csr_api/venv/lib/python3.6/site-packages/PyKCS11/__init__.py", line 483, in load
>     raise PyKCS11Error(-1, pkcs11dll_filename)
> PyKCS11.PyKCS11Error: Load (/usr/lib/softhsm/libsofthsm2.so)
> 
>

**Comment by LudovicRousseau** [comment]
What is the result of the command: `ldd -r /usr/lib/softhsm/libsofthsm2.so`

**Comment by xzr** [comment]
(venv) xzr@xzr-work:~/code/csr_api$ ldd -r /usr/lib/softhsm/libsofthsm2.so
	linux-vdso.so.1 (0x00007ffef0fa6000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007ff9c3513000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff9c318a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff9c2d99000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff9c2b81000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff9c297d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff9c275e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff9c23c0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff9c3c38000)

As said, I can actually load the library and perform operations if I drop django out of the equation. So maybe it's somehow related to how django handles strings or something. Will have to do some research

**Comment by xzr** [comment]
oh my god I am dumb. 

I had a typo in the environment variable pointing to the softhsm configuration file. I'm so sorry.

Closing as PEBCAK.

**Comment by LudovicRousseau** [comment]
:-)
