### ISSUE TITLE
softhsm 2.5 support

### ISSUE THREAD

**Issue by jasperpppp** [LudovicRousseau/PyKCS11#58]
#### Your system information

* Operating system used:
* PyKCS11 version: 1.5.3
* Python version: 3.7
* PKCS#11 library used:

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen.
All unit tests pass

Describe what _did_ happen.
Unit test test_getMechanismList failing using softhsm-2.5.0.

#### Steps for reproducing this issue:

1. Run tests

**Comment by LudovicRousseau** [comment]
It works for me.

You forgot to answer "Operating system used:"

Provide a complete copy of the error message.

**Comment by jasperpppp** [comment]
thanks
