### ISSUE TITLE
Don't install on GNU/Linux

### ISSUE THREAD

**Issue by RastaDill** [LudovicRousseau/PyKCS11#6]
Hello. I'm trying install PyKCS11 on GNU/Linux, but when i do 'make build':
src/pykcs11_wrap.cpp:171:21: фатальная ошибка: Python.h: Нет такого файла или каталога
 # include <Python.h>
                     ^
компиляция прервана.
error: command 'gcc' failed with exit status 1
Makefile:11: ошибка выполнения рецепта для цели «build-stamp»
make: *** [build-stamp] Ошибка 1

I think this bug only Windows. How fixed this?
Thanks.

**Comment by LudovicRousseau** [comment]
You need to install the package providing the `Python.h` file.
On a Debian GNU/Linux system it is `libpython3.4-dev` https://packages.debian.org/jessie/libpython3.4-dev
