### ISSUE TITLE
Manufacturer not displayed correctly for Rainbow Token

### ISSUE THREAD

**Issue by danherascu** [LudovicRousseau/PyKCS11#60]
#### Your system information

* Operating system used:  Windows 10 PRO x64
* PyKCS11 version: 1.5.5
* Python version: 3.6
* PKCS#11 library used: eTPKCS11.dll (Cryptoki 2.20, SafeNet eToken 10.0)

#### Please describe your issue in as much detail as possible:
I am trying to access information on a Rainbow Tech token, model 330.
When I use OpenSC tools for windows, for the manufacturer field I get "©Rainbow Tech.", when I use the library to get the manufacturer I only get "Rainbow Tech.", so there is a character missing. I have tried both all the samples, the result is the same.

Any ideas why it skips the first character ?

**Comment by LudovicRousseau** [comment]
Is the string "©Rainbow Tech." a valid UTF-8 string?
Can you provide an hex dump of the string for example?

**Comment by danherascu** [comment]
Well if I run `print("©Rainbow Tech.".encode("utf-8"))` I get `b'\xc2\xa9Rainbow Tech.'`.
Also if I use an older version of PyKCS11, I get
`  File "lib\site-packages\PyKCS11\LowLevel.py", line 847, in GetManufacturerID
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 0: invalid start byte`

**Comment by LudovicRousseau** [comment]
Try with PyKCS11 version 1.4.4 or lower.
Copy here the result of the commands:
```
./samples/getinfo.py
```
and
```
./samples/getinfo.py | xxd
```

**Comment by danherascu** [comment]
The output of getinfo:
`cryptokiVersion: 2.20 
flags:  
libraryDescription: b'SafeNet eToken PKCS#11          ' 
libraryVersion: 10.0 
manufacturerID: b'SafeNet, Inc.                   ' 
Available Slots: 1 [3]

Slot 1/1 (number 3):
 firmwareVersion: b'0.00' 
 flags: CKF_TOKEN_PRESENT, CKF_REMOVABLE_DEVICE, CKF_HW_SLOT 
 hardwareVersion: b'1.00' 
 manufacturerID: b'SafeNet, Inc.                   ' 
 slotDescription: b'Rainbow Technologies iKeyVirtualReader 0                        ' 
 SessionInfo 
  flags: CKF_SERIAL_SESSION 
  slotID: 3 
  state: 0 
  ulDeviceError: 0 
 TokenInfo
  firmwareVersion: 0.6 
  flags: CKF_RNG, CKF_LOGIN_REQUIRED, CKF_USER_PIN_INITIALIZED, CKF_DUAL_CRYPTO_OPERATIONS, CKF_TOKEN_INITIALIZED 
  hardwareVersion: 0.6 
  label: b'Token TEST                       ' 
  manufacturerID: b'\xa9Rainbow Tech.                  ' 
  model: b'Model 330       ' 
  serialNumber: b'90098345        ' 
  ulFreePrivateMemory: 27468 
  ulFreePublicMemory: 27468 
  ulMaxPinLen: 16 
  ulMaxRwSessionCount: 0 
  ulMaxSessionCount: 0 
  ulMinPinLen: 4 
  ulRwSessionCount: 0 
  ulSessionCount: 1 
  ulTotalPrivateMemory: 32768 
  ulTotalPublicMemory: 32768 
  utcTime: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' `

the second out:

> 00000000: 6372 7970 746f 6b69 5665 7273 696f 6e3a  cryptokiVersion:
00000010: 2032 2e32 3020 0a66 6c61 6773 3a20 200a   2.20 .flags:  .
00000020: 6c69 6272 6172 7944 6573 6372 6970 7469  libraryDescripti
00000030: 6f6e 3a20 6227 5361 6665 4e65 7420 6554  on: b'SafeNet eT
00000040: 6f6b 656e 2050 4b43 5323 3131 2020 2020  oken PKCS#11    
00000050: 2020 2020 2020 2720 0a6c 6962 7261 7279        ' .library
00000060: 5665 7273 696f 6e3a 2031 302e 3020 0a6d  Version: 10.0 .m
00000070: 616e 7566 6163 7475 7265 7249 443a 2062  anufacturerID: b
00000080: 2753 6166 654e 6574 2c20 496e 632e 2020  'SafeNet, Inc.  
00000090: 2020 2020 2020 2020 2020 2020 2020 2020                  
000000a0: 2027 200a 4176 6169 6c61 626c 6520 536c   ' .Available Sl
000000b0: 6f74 733a 2031 205b 335d 0a0a 536c 6f74  ots: 1 [3]..Slot
000000c0: 2031 2f31 2028 6e75 6d62 6572 2033 293a   1/1 (number 3):
000000d0: 0a20 6669 726d 7761 7265 5665 7273 696f  . firmwareVersio
000000e0: 6e3a 2062 2730 2e30 3027 200a 2066 6c61  n: b'0.00' . fla
000000f0: 6773 3a20 434b 465f 544f 4b45 4e5f 5052  gs: CKF_TOKEN_PR
00000100: 4553 454e 542c 2043 4b46 5f52 454d 4f56  ESENT, CKF_REMOV
00000110: 4142 4c45 5f44 4556 4943 452c 2043 4b46  ABLE_DEVICE, CKF
00000120: 5f48 575f 534c 4f54 200a 2068 6172 6477  _HW_SLOT . hardw
00000130: 6172 6556 6572 7369 6f6e 3a20 6227 312e  areVersion: b'1.
00000140: 3030 2720 0a20 6d61 6e75 6661 6374 7572  00' . manufactur
00000150: 6572 4944 3a20 6227 5361 6665 4e65 742c  erID: b'SafeNet,
00000160: 2049 6e63 2e20 2020 2020 2020 2020 2020   Inc.           
00000170: 2020 2020 2020 2020 2720 0a20 736c 6f74          ' . slot
00000180: 4465 7363 7269 7074 696f 6e3a 2062 2752  Description: b'R
00000190: 6169 6e62 6f77 2054 6563 686e 6f6c 6f67  ainbow Technolog
000001a0: 6965 7320 694b 6579 5669 7274 7561 6c52  ies iKeyVirtualR
000001b0: 6561 6465 7220 3020 2020 2020 2020 2020  eader 0         
000001c0: 2020 2020 2020 2020 2020 2020 2020 2027                 '
000001d0: 200a 2053 6573 7369 6f6e 496e 666f 200a   . SessionInfo .
000001e0: 2020 666c 6167 733a 2043 4b46 5f53 4552    flags: CKF_SER
000001f0: 4941 4c5f 5345 5353 494f 4e20 0a20 2073  IAL_SESSION .  s
00000200: 6c6f 7449 443a 2033 200a 2020 7374 6174  lotID: 3 .  stat
00000210: 653a 2030 200a 2020 756c 4465 7669 6365  e: 0 .  ulDevice
00000220: 4572 726f 723a 2030 200a 2054 6f6b 656e  Error: 0 . Token
00000230: 496e 666f 0a20 2066 6972 6d77 6172 6556  Info.  firmwareV
00000240: 6572 7369 6f6e 3a20 302e 3620 0a20 2066  ersion: 0.6 .  f
00000250: 6c61 6773 3a20 434b 465f 524e 472c 2043  lags: CKF_RNG, C
00000260: 4b46 5f4c 4f47 494e 5f52 4551 5549 5245  KF_LOGIN_REQUIRE
00000270: 442c 2043 4b46 5f55 5345 525f 5049 4e5f  D, CKF_USER_PIN_
00000280: 494e 4954 4941 4c49 5a45 442c 2043 4b46  INITIALIZED, CKF
00000290: 5f44 5541 4c5f 4352 5950 544f 5f4f 5045  _DUAL_CRYPTO_OPE
000002a0: 5241 5449 4f4e 532c 2043 4b46 5f54 4f4b  RATIONS, CKF_TOK
000002b0: 454e 5f49 4e49 5449 414c 495a 4544 200a  EN_INITIALIZED .
000002c0: 2020 6861 7264 7761 7265 5665 7273 696f    hardwareVersio
000002d0: 6e3a 2030 2e36 200a 2020 6c61 6265 6c3a  n: 0.6 .  label:
000002e0: 2062 2754 6f6b 656e 2054 4553 5420 2020   b'Token TEST   
000002f0: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000300: 2020 2020 2720 0a20 206d 616e 7566 6163      ' .  manufac
00000310: 7475 7265 7249 443a 2062 275c 7861 3952  turerID: b'\xa9R
00000320: 6169 6e62 6f77 2054 6563 682e 2020 2020  ainbow Tech.    
00000330: 2020 2020 2020 2020 2020 2020 2020 2720                ' 
00000340: 0a20 206d 6f64 656c 3a20 6227 4d6f 6465  .  model: b'Mode
00000350: 6c20 3333 3020 2020 2020 2020 2720 0a20  l 330       ' . 
00000360: 2073 6572 6961 6c4e 756d 6265 723a 2062   serialNumber: b
00000370: 2739 3030 3938 3334 3520 2020 2020 2020  '90098345       
00000380: 2027 200a 2020 756c 4672 6565 5072 6976   ' .  ulFreePriv
00000390: 6174 654d 656d 6f72 793a 2032 3734 3638  ateMemory: 27468
000003a0: 200a 2020 756c 4672 6565 5075 626c 6963   .  ulFreePublic
000003b0: 4d65 6d6f 7279 3a20 3237 3436 3820 0a20  Memory: 27468 . 
000003c0: 2075 6c4d 6178 5069 6e4c 656e 3a20 3136   ulMaxPinLen: 16
000003d0: 200a 2020 756c 4d61 7852 7753 6573 7369   .  ulMaxRwSessi
000003e0: 6f6e 436f 756e 743a 2030 200a 2020 756c  onCount: 0 .  ul
000003f0: 4d61 7853 6573 7369 6f6e 436f 756e 743a  MaxSessionCount:
00000400: 2030 200a 2020 756c 4d69 6e50 696e 4c65   0 .  ulMinPinLe
00000410: 6e3a 2034 200a 2020 756c 5277 5365 7373  n: 4 .  ulRwSess
00000420: 696f 6e43 6f75 6e74 3a20 3020 0a20 2075  ionCount: 0 .  u
00000430: 6c53 6573 7369 6f6e 436f 756e 743a 2031  lSessionCount: 1
00000440: 200a 2020 756c 546f 7461 6c50 7269 7661   .  ulTotalPriva
00000450: 7465 4d65 6d6f 7279 3a20 3332 3736 3820  teMemory: 32768 
00000460: 0a20 2075 6c54 6f74 616c 5075 626c 6963  .  ulTotalPublic
00000470: 4d65 6d6f 7279 3a20 3332 3736 3820 0a20  Memory: 32768 . 
00000480: 2075 7463 5469 6d65 3a20 6227 5c78 3030   utcTime: b'\x00
00000490: 5c78 3030 5c78 3030 5c78 3030 5c78 3030  \x00\x00\x00\x00
000004a0: 5c78 3030 5c78 3030 5c78 3030 5c78 3030  \x00\x00\x00\x00
000004b0: 5c78 3030 5c78 3030 5c78 3030 5c78 3030  \x00\x00\x00\x00
000004c0: 5c78 3030 5c78 3030 5c78 3030 2720       \x00\x00\x00'

**Comment by LudovicRousseau** [comment]
The "©" character is encoded in UTF-8 as 0xC2 0xA9.
http://www.fileformat.info/info/unicode/char/a9/index.htm

0xA9 (without the 0xC2) is the Latin-1 or ISO-8859-1 encoding.

The `CK_SLOT_INFO` structure is defined as:
```
typedef struct CK_SLOT_INFO {
     CK_UTF8CHAR slotDescription[64];
     CK_UTF8CHAR manufacturerID[32];
     CK_FLAGS flags;
     CK_VERSION hardwareVersion;
     CK_VERSION firmwareVersion;
   } CK_SLOT_INFO;
```

`manufacturerID` is defined as an array of `CK_UTF8CHAR`. The problem is that your PKCS#11 library returns a **non-valid** UTF-8 string.

You should report the problem to your PKCS#11 provider. The problem is not in PyKCS11.
