### ISSUE TITLE
Fail to install by sudo pip install PyKCS11==1.5.5

### ISSUE THREAD

**Issue by sepulm01** [LudovicRousseau/PyKCS11#62]
#### Your system information

* Operating system used: Ubuntu 18.04.2 LTS
* PyKCS11 version: 1.5.5
* Python version: 3.6.8
* PKCS#11 library used: ?

#### Please describe your issue in as much detail as possible:
 I try to use :
sudo pip3 install PyKCS11==1.5.5. I've install in my personal computer , but when to replicate the installation on Google VM I couldn't.
best regards.

Describe what you _expected_ should happen.

Describe what _did_ happen.

Collecting PyKCS11==1.5.5
  Downloading https://files.pythonhosted.org/packages/f6/a0/2800ff56c0b3856d1af410f8494836672339d7566d975a62bf81a4ad5716/PyKCS11-1.5.5.tar.gz (72kB)
     |████████████████████████████████| 81kB 3.6MB/s 
Building wheels for collected packages: PyKCS11
  Building wheel for PyKCS11 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5cd9rxsk/PyKCS11/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5cd9rxsk/PyKCS11/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-exjwa9at --python-tag cp36
       cwd: /tmp/pip-install-5cd9rxsk/PyKCS11/
  Complete output (8 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'PyKCS11._LowLevel' extension
  swigging src/pykcs11.i to src/pykcs11_wrap.cpp
  swig -python -c++ -o src/pykcs11_wrap.cpp src/pykcs11.i
  unable to execute 'swig': No such file or directory
  error: command 'swig' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for PyKCS11
  Running setup.py clean for PyKCS11
Failed to build PyKCS11
Installing collected packages: PyKCS11
  Running setup.py install for PyKCS11 ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5cd9rxsk/PyKCS11/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5cd9rxsk/PyKCS11/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-awbz8nrq/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-5cd9rxsk/PyKCS11/
    Complete output (8 lines):
    running install
    running build
    running build_ext
    building 'PyKCS11._LowLevel' extension
    swigging src/pykcs11.i to src/pykcs11_wrap.cpp
    swig -python -c++ -o src/pykcs11_wrap.cpp src/pykcs11.i
    unable to execute 'swig': No such file or directory
    error: command 'swig' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5cd9rxsk/PyKCS11/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5cd9rxsk/PyKCS11/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-awbz8nrq/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

#### Steps for reproducing this issue:

1. sudo pip3 install PyKCS11==1.5.5
2. 
3.

**Comment by LudovicRousseau** [comment]
`unable to execute 'swig': No such file or directory`

install swig.

**Comment by sepulm01** [comment]
Thank a lot, it works!

**Comment by contactoften** [comment]
HI Same error in AZURE

unning setup.py install for PyKCS11: finished with status 'error'
[20:16:47+0000]     Complete output from command /tmp/8d873a198736bb9/antenv3.6/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vaf5gt2p/PyKCS11/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-qnnpxwaq/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/8d873a198736bb9/antenv3.6/include/site/python3.6/PyKCS11:
[20:16:47+0000]     running install
[20:16:47+0000]     running build
[20:16:47+0000]     running build_ext
[20:16:47+0000]     building 'PyKCS11._LowLevel' extension
[20:16:47+0000]     swigging src/pykcs11.i to src/pykcs11_wrap.cpp
[20:16:47+0000]     swig -python -c++ -o src/pykcs11_wrap.cpp src/pykcs11.i
[20:16:47+0000]     unable to execute 'swig': Permission denied
[20:16:47+0000]     error: command 'swig' failed with exit status 1
[20:16:47+0000]     
[20:16:47+0000]     ----------------------------------------

How do I Resolve... Please help

**Comment by LudovicRousseau** [comment]
@contactoften If you have the same error, maybe you can use the same solution?

**Comment by contactoften** [comment]
How do I install in Microsoft AZURE

**Comment by LudovicRousseau** [comment]
@contactoften Contact me by email ludovic.rousseau@free.fr
