### ISSUE TITLE
LoadLibrary() failed with error 126: The specified module could not be found

### ISSUE THREAD

**Issue by mxmujeeb2** [LudovicRousseau/PyKCS11#63]
#### Your system information

* Operating system used: Windows
* PyKCS11 version: latest
* Python version:  3.6
* PKCS#11 library used: cknfast

i have loaded the cknfast64 bit library in the environment variable. Then i wrote just 2 lines of code as below

pkcs11 = PyKCS11Lib()
pkcs11.load()

it gave me the error:

LTraceback (most recent call last):
  File "E:\DATA-WIDE\DATAWIDE SOLUTION\python\pkcs.py", line 10, in <module>
oadLibrary() failed with error 126: The specified module could not be found.

    pkcs11.load()
  File "C:\Users\md\AppData\Local\Programs\Python\Python36\lib\site-packages\PyKCS11\__init__.py", line 483, in load
    raise PyKCS11Error(-1, pkcs11dll_filename)
PyKCS11.PyKCS11Error: Load ("C:\Program Files (x86)\nCipher\nfast\toolkits\pkcs11\cknfast-64.dll")
[Finished in 0.2s with exit code 1]
[shell_cmd: python -u "E:\DATA-WIDE\DATAWIDE SOLUTION\python\pkcs.py"]
[dir: E:\DATA-WIDE\DATAWIDE SOLUTION\python]

**Comment by LudovicRousseau** [comment]
It looks like the file `C:\Program Files (x86)\nCipher\nfast\toolkits\pkcs11\cknfast-64.dll` does **not** exist.
Check the name is correct.

**Comment by mxmujeeb2** [comment]
I checked the file it exists , just to check its existence through the code i wrote below lines in python to check :

**libCalc = cdll.LoadLibrary("C:\\Program Files (x86)\\nCipher\\nfast\\toolkits\\pkcs11\\cknfast-64.dll")
print(libCalc)
libCalc.C_Login()**

**OUTPUT:**
<CDLL 'C:\Program Files (x86)\nCipher\nfast\toolkits\pkcs11\cknfast-64.dll', handle 7ffa3c4c0000 at 0x139871ff7f0>

Also i wanted to know src of your library "PyKCS11.LowLevel" because i wanted to know the details about how it actually communicates like if i need to use first C_Login()  or C_initialize

**Comment by LudovicRousseau** [comment]
Try again with a PyKCS lib from https://ci.appveyor.com/project/LudovicRousseau/pykcs11-debug-lfdn4/build/job/x295auqw168mep6k/artifacts

Send me the full output of your test program.

**Comment by mxmujeeb2** [comment]
In your samples/generate.py  you have shown an example of **generateKeyPair**  with PUBLIC and PRIVATE Template. Can you please pass me a sample in which you generated symmetric key and use the

**Comment by LudovicRousseau** [comment]
Why have you closed the issue?
It was a problem on your side?
