### ISSUE TITLE
Getting poor performance for bulk tokenization

### ISSUE THREAD

**Issue by mxmujeeb2** [LudovicRousseau/PyKCS11#64]
#### Your system information

# * Operating system used: Windows 10 64bit
# * PyKCS11 version: 1.5.5
# * Python version: 3.6
# * PKCS#11 library used: nCipher\nfast\toolkits\pkcs11\cknfast-64.dll

# I have a situation where there are files of 7 - 8 million rows with 200 column csv delimited with "%@$" . I have to ONLY tokenize the 2nd column  which has a 20digit number for all the 7 - 8 million rows. I am using below code but I am getting very poor performance for tokenization. The tokenization rate is: -
# SOFTHSM: 3500(tokens/s)   
# NCipherHSM : 1500(tokens/s)  

# I dont know if i am implementing the pykcs11 library in a wrong way or if there is a better way to bulk push data (array or list etc)  to tokenize quickly because the NCIPHER device i am connected has the capability of tokenizing almost 12000 - 14000 tokens/s and i am not able to get the intended performance. Atleast If i do a local AES 128 bit tokenization using pycryptodome library I am getting almost 12000 - 13000 tokens/s rate. Please advise : 

```
from PyKCS11 import *
import os
from ctypes import *
import binascii
from Cryptodome.Util.Padding import pad, unpad
from base64 import b64decode
from base64 import b64encode
from Cryptodome.Cipher import AES

mode = PyKCS11.CKM_AES_CBC
iv = b'This is an IV456'
keyLabel = "TestAESKey1"
mechanism = PyKCS11.Mechanism(mode, iv)
key = session.findObjects(
    [(PyKCS11.CKA_CLASS, PyKCS11.CKO_SECRET_KEY), (PyKCS11.CKA_LABEL, keyLabel)]
)[0]

def TokenizeNCipher( key, mode, iv, message):
	padedEncoded = pad(message.encode('utf8'), AES.block_size)  # i need to do padding if the input MSG is not 16 OR 32 bit
	ciphertext = session.encrypt(key, padedEncoded, mechanism)
	TMessage = b64encode(bytes(tuple(ciphertext))).decode("utf-8")  # the tokenized value should be alphanumeric not too long string to store
	return TMessage



with open(OriginalFileName, 'r') as Originalfile:
	with open(TokenizedFileName, 'w') as TokenizedFile:
		for line in Originalfile:
			array1 = line.split("%@$")    # this is a delimited file with 200 columns
			array1[1]=TokenizeNCipher(key, mode, iv, array1[1].strip())   # only 1st column needs to get tokenized
			newLine ='%@$'.join(array1)
			TokenizedFile.write(newLine)		# i only updated the 1st column with the tokenized value
```

**Comment by mxmujeeb2** [comment]
Can you also advise me if AES_CBC mode has best performance if i want to the tokenization to be PCI-DSS Compliant or if there is a much better mode that can give better performance keeping in consideration for the PCI-DSS. Kindly advise

**Comment by mxmujeeb2** [comment]
just to mention that i am opening the session only at the beginning of the operation and closing it at the end after it did the encryption for all the rows. Thanks

**Comment by LudovicRousseau** [comment]
The github issue tracker is not a support or consulting service.
You can contact me privately if you want.
