### ISSUE TITLE
does not build since 1.5.4

### ISSUE THREAD

**Issue by hc7** [LudovicRousseau/PyKCS11#65]
#### Your system information

* Operating system used: windows server 2016
* PyKCS11 version: 1.5.5
* Python version: 3.8
* PKCS#11 library used:

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen.

  C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86\rc.exe -Isrc -Ic:\python38\include -Ic:\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /fobuild\temp.win-amd64-3.8\Release\pykcs11.res pykcs11.rc

Compile without errors.

Describe what _did_ happen.

    C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86\rc.exe -Isrc -Ic:\python38\include -Ic:\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /fobuild\temp.win-amd64-3.8\Release\pykcs11.res pykcs11.rc
    Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
    Copyright (C) Microsoft Corporation.  All rights reserved.

    fatal error RC1110: could not open pykcs11.rc
    error: command 'C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.18362.0\\x86\\rc.exe' failed with exit status 1

#### Steps for reproducing this issue:

1. pip install -v pykcs11==1.5.5

**Comment by LudovicRousseau** [comment]
Fixed in https://github.com/LudovicRousseau/PyKCS11/commit/d348a5f8581e862b133327936af65c4e3f16aa29

A new release is in progress
