### ISSUE TITLE
Building 1.5.6 fail 

### ISSUE THREAD

**Issue by hc7** [LudovicRousseau/PyKCS11#66]
#### Your system information

* Operating system used: windows server 2016
* PyKCS11 version: 1.5.6
* Python version: 3.8
* PKCS#11 library used:

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen.

Resource compiler **should** find resource.h also. 

Describe what _did_ happen.

  pykcs11.rc(3) : fatal error RC1015: cannot open include file 'resource.h'.
  error: command 'C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.18362.0\\x86\\rc.exe' failed with exit status 1
error
  ERROR: Failed building wheel for PyKCS11

![image](https://user-images.githubusercontent.com/3115201/71101839-6e8afe00-21c8-11ea-9d98-03cafdb18e73.png)

#### Steps for reproducing this issue:

1. pip wheel -v --wheel-dir=D:\work --no-binary :all: PyKCS11

**Comment by LudovicRousseau** [comment]
Fixed in https://github.com/LudovicRousseau/PyKCS11/commit/7e837c81d16a98ddf791831b51da972904942f21

I also made a new release. It _should_ be OK now.

**Comment by hc7** [comment]
It is build as expected now. Thanks a lot!
