### ISSUE TITLE
Question - pyopenssl, requests, and this module together!

### ISSUE THREAD

**Issue by danizen** [LudovicRousseau/PyKCS11#68]
#### What Works?

PyKCS11 worked admirably for me subject to me knowledge and limitations.  I am able to itemize the X509 certificates, private keys, etc. on my NIH provided smart card, and one colleague on OS X can do the same having carefully installed opensc.

Thanks for providing this module.

#### Since it works, what Feature do I want?

I need to authenticate against an internal NIH web application that is secured using TLS and wants me (my users actually) to use a client certifcate on the smart card.  I'm looking for some advise on creating a mash-up between Python requests (or requests-toolbelt), pyopenssl, and this module.  

Since openssl itself is sometimes compiled without PKCS11 support, it isn't clear this is even feasible using just Python.  I am filing this bug to peel the onion.

#### Your system information

* Operating system used: Windows 10
* PyKCS11 version: 1.5.5
* Python version: CPython 3.6.8
* PKCS#11 library used: C:\Program Files\HID Global\ActivClient\acpkcs211.dll

A friend using OS X Mojave is using opensc provided library in /Library/Frameworks/ac.ac4mac.pkcs11.framework/Versions/Current/Libraries/apkcs220.dylib

__Describe what you _expected_ should happen__:
I'm not looking for miracles here - I open issues on github because maybe there's a project somewhere that already does what I need to do, and I haven't found it yet.

__Describe what _did_ happen__:

Developer wonders in the shadow of the valley of night, trying pywin32, ctypes, anything to access the certificate on his smart card.  Developer ultimately succeeds in finding and using this module, only to realize he has to *implement* SSL based on a low-level library to find a solution.  Developer knows that this will ultimately lead to failure unless he can not only implement a solution of find the correct open source framework to which to contribute it.

#### Steps for reproducing this issue:

1. Howl in darkness for a year
2. Install and use PKCS#11 correctly
3. Realize that the smart card's private key is still privately on the smart card, and so you won't get it done just by supplying certificate and keypair path to Python requests.
4. Realize that even requests-toolbelt's class X509Adapter still requires access to the bytes of the request.
5. Ask for help from experts in cryptography.

**Comment by LudovicRousseau** [comment]
Have you tried to use OpenSSL with the PKCS#11 engine?
https://github.com/OpenSC/libp11

**Comment by danizen** [comment]
@LudovicRousseau, I'm not sure how that will help me. Can you explain more?  

Let me also explain what I am trying to accomplish.  I have an internal Python cli tool which works very much like https://github.com/trek10inc/awsume, but it is more targeted to our particular environment.   The user installs the tool via pip, and then runs the CLI to update their AWS credentials, and is prompted for a password.  The code then goes to a web page that is secured by either password or PIV.  Currently, my code chooses password, and then posts a username and password.   My code then retrieves a SAML certificate from a form that would be auto-posted to AWS console login.  Eventually, the code calls assumeRoleWithSaml AWS API, and then stores credentials in ~/.aws/credentials under a named profile.

The requirement is to support PIV login with this process, but the strongest requirement is to do this on Windows.  In fact, my motivation is that if my tool supports PIV, then users who currently use my tool for CLI access from Linux won't have to switch to a Windows only solution.

So, I'm half-way convinced I'll do better to write a requests HTTPAdapter that uses WinHTTP through ctypes or cffi, but then I won't help colleagues who use OS X, or push the state of the art further.

I'm willing to struggle with distributing a version of OpenSSL and OpenSC that solves this problem - we used to use binary versions of lxml built by me to support Windows development before the manylinux1 PEP.

**Comment by LudovicRousseau** [comment]
The issue tracker is for issues.
Contact me by email if you need support.

**Comment by danizen** [comment]
I will follow up via email if what you suggested doesn't work, or if I have trouble doing it having found https://github.com/OpenSC/libp11 on a day with fewer distractions.

**Comment by ubalklen** [comment]
Hi @danizen! I'm still howling in darkness. Have you eventually found some solution? I'm doing what I can with `pywin32`, but I would love to use something nicely integrated to `requests`.
