### ISSUE TITLE
Fail to load .so in both in MAC & Ubuntu

### ISSUE THREAD

**Issue by applezhp** [LudovicRousseau/PyKCS11#69]
#### Your system information

* Operating system used: MAC Catalina 10.15.2  & Ubuntu 16.04
* PyKCS11 version: 1.5.7
* Python version: Ubuntu 3.5 , Mac 3.7.4
* PKCS#11 library used:
_LowLevel.cpython-35m-x86_64-linux-gnu.so
_LowLevel.cpython-37m-darwin.so

#### Please describe your issue in as much detail as possible:
src/dyn_unix.c:76:SYS_dyn_GetAddress() C_GetFunctionList: dlsym(0x7fe0fd4310c0, C_GetFunctionList): symbol not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyKCS11/__init__.py", line 484, in load
    raise PyKCS11Error(rv, pkcs11dll_filename)
PyKCS11.PyKCS11Error: C_GetFunctionList() not found (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyKCS11/_LowLevel.cpython-37m-darwin.so)
#### Steps for reproducing this issue:
1.  pip install PyKCS11
2. import PyKCS11
3. pkcs11 =PyKCS11.PyKCS11Lib()
4. pkcs11.load('xxx.so')

**Comment by LudovicRousseau** [comment]
`_LowLevel.cpython-35m-x86_64-linux-gnu.so` and `_LowLevel.cpython-37m-darwin.so` are **NOT** PKCS#11 libraries. They are part of the wrapper and are used internally.

PyKCS11 does NOT provide a PKCS#11 library.
You need to install one yourself. Like OpenSC https://github.com/OpenSC/OpenSC/wiki or SoftHSM https://www.opendnssec.org/softhsm/.

**Comment by applezhp** [comment]
Got it, try to install the opensc now.

**Comment by applezhp** [comment]
Finally I got the .so package from the supplier, it works! My U-token is epass2000Auto by Feitian. If somebody else need the .so file for linux, I can share it!
