### ISSUE TITLE
No module named _LowLevel and Failed to install PyKCS11 1.5 via tar.gz

### ISSUE THREAD

**Issue by snny000** [LudovicRousseau/PyKCS11#70]
* Operating system used: Centos7.5
* PyKCS11 version: 1.5.7
* Python version: python2.7
* PKCS#11 library used: PyKCS11-1.5.7.tar.gz
Failed to install PyKCS11 1.5.7 via python setup.py install.

 Steps for reproducing this issue:

1. download the PyKCS11 1.5.7 lib by https://files.pythonhosted.org/packages/92/53/6655729684fafc171b86a307e2650010c09a3266d96f5907151d75a16d9f/PyKCS11-1.5.7.tar.gz
2.  tar -zxvf PyKCS11-1.5.7.tar.gz
3. cd PyKCS11-1.5.7
4. python setup.py install

result:

from PyKCS11 import *

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PyKCS11/__init__.py", line 20, in <module>
    import PyKCS11.LowLevel
  File "PyKCS11/LowLevel.py", line 21, in <module>
    _LowLevel = swig_import_helper()
  File "PyKCS11/LowLevel.py", line 20, in swig_import_helper
    return importlib.import_module('_LowLevel')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _LowLevel

**Comment by LudovicRousseau** [comment]
Be sure to be OUTSIDE of the PyKCS11-1.5.7 directory to make your test.

**Comment by snny000** [comment]
That works. Thanks

> Be sure to be OUTSIDE of the PyKCS11-1.5.7 directory to make your test.
