### ISSUE TITLE
Failed building wheel for PyKCS11

### ISSUE THREAD

**Issue by vraj72** [LudovicRousseau/PyKCS11#71]
#### Your system information

* Operating system used: ubuntu
* PyKCS11 version:
* Python version: 3
* PKCS#11 library used:

#### Please describe your issue in as much detail as possible:
 pip3 install PyKCS11
Collecting PyKCS11
  Using cached https://files.pythonhosted.org/packages/92/53/6655729684fafc171b86a307e2650010c09a3266d96f5907151d75a16d9f/PyKCS11-1.5.7.tar.gz
Building wheels for collected packages: PyKCS11
  Running setup.py bdist_wheel for PyKCS11 ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qajg73ni/PyKCS11/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmprzdt0imcpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'PyKCS11._LowLevel' extension
  swigging src/pykcs11.i to src/pykcs11_wrap.cpp
  swig -python -c++ -o src/pykcs11_wrap.cpp src/pykcs11.i
  unable to execute 'swig': No such file or directory
  error: command 'swig' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for PyKCS11
  Running setup.py clean for PyKCS11
Failed to build PyKCS11
Installing collected packages: PyKCS11
  Running setup.py install for PyKCS11 ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qajg73ni/PyKCS11/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-u1uyi6aa-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'PyKCS11._LowLevel' extension
    swigging src/pykcs11.i to src/pykcs11_wrap.cpp
    swig -python -c++ -o src/pykcs11_wrap.cpp src/pykcs11.i
    unable to execute 'swig': No such file or directory
    error: command 'swig' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qajg73ni/PyKCS11/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-u1uyi6aa-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-qajg73ni/PyKCS11/

Describe what you _expected_ should happen.

Describe what _did_ happen.

#### Steps for reproducing this issue:

1.  pip3 install PyKCS11

**Comment by LudovicRousseau** [comment]
```
 unable to execute 'swig': No such file or directory
```
install swig and try again.

You can also install the python3-pykcs11 Ubuntu package
https://packages.ubuntu.com/search?keywords=python3-pykcs11

**Comment by erny** [comment]
I just came here with the same error. Swig IS installed in virtualenv. Anyhow pythonpath is cleared before swig is launched, so any installed packages can't be found. 

I was able to install with:  `pip install --no-build-isolation pykcs11`

**Comment by LudovicRousseau** [comment]
@erny I already provide (Windows) wheels at https://pypi.org/project/PyKCS11/#files

For Ubuntu I recommand to use the package [python3-pykcs11](https://packages.ubuntu.com/search?keywords=python3-pykcs11)
