### ISSUE TITLE
trouble using PyKCS11 with libbeidpkcs11

### ISSUE THREAD

**Issue by linuxunderground** [LudovicRousseau/PyKCS11#73]
#### Your system information

* Operating system used: Gentoo linux
* PyKCS11 version: 1.5.8
* Python version: 3.8
* PKCS#11 library used: libbeidpkcs11 version 5.0+

#### Please describe your issue in as much detail as possible:
You will find all the explanations here : [https://github.com/Fedict/eid-mw/issues/118](https://github.com/Fedict/eid-mw/issues/118)

Describe what _did_ happen.
No slots can be found (regardless of whether they have a token or not).

#### Steps for reproducing this issue:

Simple python script here [https://github.com/linuxunderground/eid-mw-sdk-python](https://github.com/linuxunderground/eid-mw-sdk-python)

**Comment by LudovicRousseau** [comment]
I think I fixed the problem in the `devel` branch of the `PyKCS11-debug` project.

Can you use https://github.com/LudovicRousseau/PyKCS11-debug/tree/devel and try to reproduce the problem?

**Comment by linuxunderground** [comment]
Problem is well fixed in your debug branch.
I wait for the official release with impatience...

**Comment by LudovicRousseau** [comment]
Fixed in release 1.5.9
https://ludovicrousseau.blogspot.com/2020/07/new-pykcs11-159-available.html
