### ISSUE TITLE
Wheels for Python 3.9

### ISSUE THREAD

**Issue by qdamian** [LudovicRousseau/PyKCS11#78]
#### Your system information

* Operating system used: Windows 10 x64
* PyKCS11 version: 1.5.9
* Python version: 3.9.0
* PKCS#11 library used: -

#### Please describe your issue in as much detail as possible:
I was trying to install pykcs11 on Windows but it requires 'swig.exe'. I was hoping there would be wheels for Python 3.9, as there are for other versions. In our case we need the ones for cp39-win_amd64.

#### Steps for reproducing this issue:

1. pip install pykcs11==1.5.9

**Comment by LudovicRousseau** [comment]
Python 3.9 is not yet available in AppVeyor.
I tried but it failed: https://ci.appveyor.com/project/LudovicRousseau/pykcs11-debug-lfdn4/build/job/cl4araw869s2yd25

**Comment by LudovicRousseau** [comment]
Wheel for Python 3.9 + Windows is now available for PyKCS11 1.5.10
https://pypi.org/project/PyKCS11/#files
