### ISSUE TITLE
The specified module could not be found error while loading "_LowLevel.cp38-win_amd64.pyd"

### ISSUE THREAD

**Issue by kalyank23** [LudovicRousseau/PyKCS11#79]
#### Your system information

* Operating system used:
* PyKCS11 version: 1.5.9
* Python version: 3.8.6
* PKCS#11 library used:

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen.
I expected it to load the low level library

Describe what _did_ happen.
Got the error as "ImportError: DLL load failed while importing _LowLevel: The specified module could not be found."

How do I debug such errors? Is it because of a missing Dll file in my windows operating system? or due to incompatible Dll version?

I am using Windows Enterprise Edition.

If some dependency issue, it would not have installed itself, but it installed and causing the above error

```
............\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "PyKCS11\LowLevel.py", line 28, in <module>
  File "PyKCS11\LowLevel.py", line 20, in swig_import_helper
ImportError: DLL load failed while importing _LowLevel: The specified module could not be found.
[14068] Failed to execute script 
```

**Comment by LudovicRousseau** [comment]
Show me your code.
