### ISSUE TITLE
init_token low level sample fails at C_Login(SO)

### ISSUE THREAD

**Issue by DavidTWhite** [LudovicRousseau/PyKCS11#8]
Output: 

Load of /usr/lib/pkcs11/libopencryptoki.so: True
C_GetInfo: 0x0
Library manufacturerID: IBM                             
C_GetSlotList(NULL): 0x0
	Available Slots: 2
	C_SlotInfo(): 0x0
	C_GetTokenInfo(): 0x0
		TokenInfo: Label=IBM PKCS#11 TPM Token           , ManufacturerID=IBM Corp.                       
		TokenInfo: flags=0x880045, Model=TPM v1.1 Token  
	C_InitToken(): 0xa0
	C_GetTokenInfo(): 0x0
		TokenInfo: Label=IBM PKCS#11 TPM Token           , ManufacturerID=IBM Corp.                       
		TokenInfo: flags=0x880045, Model=TPM v1.1 Token  
	C_OpenSession(): 0x0
		Session:<PyKCS11.LowLevel.CK_SESSION_HANDLE; proxy of <Swig Object of type 'CK_SESSION_HANDLE *' at 0xb771a7e8> >
	C_GetSessionInfo(): 0x0
		SessionInfo: state=0x2, flags=0x6
	C_Login(SO): 0xa0
	C_InitPIN(): 0x101
	C_Logout(SO): 0x101
	C_GetTokenInfo(): 0x0
		TokenInfo: Label=IBM PKCS#11 TPM Token           , ManufacturerID=IBM Corp.                       
		TokenInfo: flags=0x980045, Model=TPM v1.1 Token  
C_Login(USER): 0x102
C_Logout(USER): 0x101
C_CloseSession(): 0x0
C_Finalize(): 0x0
True

**Comment by DavidTWhite** [comment]
My issue appears to be stemming from a deeper level than PyKCS11 actually. Closing.

**Comment by applezhp** [comment]
I have a similar output as:

C_GetInfo: 0x0
Library manufacturerID: Feitian Technologies Co., Ltd.  
C_GetSlotList(NULL): 0x0
	Available Slots: 1
	C_SlotInfo(): 0x0
	C_GetTokenInfo(): 0x0
		TokenInfo: Label=ePass Token                     , ManufacturerID=Feitian Technologies Co., Ltd.  
		TokenInfo: flags=0xc9040c, Model=ePass2000Auto   
	C_InitToken(): 0xa4
	C_GetTokenInfo(): 0x0
		TokenInfo: Label=ePass Token                     , ManufacturerID=Feitian Technologies Co., Ltd.  
		TokenInfo: flags=0xc9040c, Model=ePass2000Auto   
	C_OpenSession(): 0x0
		Session:<PyKCS11.LowLevel.CK_SESSION_HANDLE; proxy of <Swig Object of type 'CK_SESSION_HANDLE *' at 0x7f6fab60a570> >
	C_GetSessionInfo(): 0x0
		SessionInfo: state=0x2, flags=0x6
	C_Login(SO): 0xa4
	C_InitPIN(): 0x101
	C_Logout(SO): 0x101
	C_GetTokenInfo(): 0x0
		TokenInfo: Label=ePass Token                     , ManufacturerID=Feitian Technologies Co., Ltd.  
		TokenInfo: flags=0xc9040c, Model=ePass2000Auto   
C_Login(USER): 0xa0
C_Logout(USER): 0x101
C_CloseSession(): 0x0
C_Finalize(): 0x0
True

________________________

BTW, the so works well for RSA sign purpose

**Comment by LudovicRousseau** [comment]
@applezhp this issue is closed.
Open a new one and provide the requested information if you really have a problem.
