### ISSUE TITLE
Time to sign 

### ISSUE THREAD

**Issue by SantiagoAndresHurtado** [LudovicRousseau/PyKCS11#80]
#### Your system information

* Operating system used: Centos8
* PyKCS11 version:  1.5.9
* Python version: 3.8
* PKCS#11 library used: [librarylibcastle.zip](https://github.com/LudovicRousseau/PyKCS11/files/5539444/librarylibcastle.zip)

#### Please describe your issue in as much detail as possible:
I already sign and get certificate with many tokens (epass2003), but the problem is that this takes me 10 seconds each process. 

is there any way to reduce the time?

**Comment by LudovicRousseau** [comment]
Contact me by email if you want specific support.
