### ISSUE TITLE
Sample template for generating P-384 EC keypair

### ISSUE THREAD

**Issue by kalyank23** [LudovicRousseau/PyKCS11#81]
#### Your system information

* Operating system used: Windows
* PyKCS11 version: 2.0.12
* Python version: 3.8
* PKCS#11 library used: Yubikey

#### Please describe your issue in as much detail as possible:
**Describe what you _expected_ should happen.** Should be able to generate the EC keypair

**Describe what _did_ happen.** TypeError: in method 'CK_ATTRIBUTE_SMART_SetBin', argument 3 of type 'std::vector< unsigned char > const &'

#### Steps for reproducing this issue:

1. We have used the below template to generate key pair
[(CKA_CLASS, CKO_PUBLIC_KEY), (CKA_ID, cka_id),
(CKA_KEY_TYPE, CKK_EC), (CKA_TOKEN, CK_TRUE),
(CKA_PRIVATE, CK_FALSE),
(CKA_EC_PARAMS, [('namedCurve', 'secp384r1')])]

Could you let me know how to pass CKA_EC_PARAMS?

**Comment by LudovicRousseau** [comment]
Have you looked at https://github.com/LudovicRousseau/PyKCS11/blob/master/samples/ec_generate.py ?

**Comment by manojyadlapalli** [comment]
Thanks, It works now.
