### ISSUE TITLE
Exctract the content of an object and display it in human-readable format

### ISSUE THREAD

**Issue by amitraky** [LudovicRousseau/PyKCS11#82]
I am trying to extract subject information and put it in pdf signature from the certificate but it's not so ....  have any solution for this 
Thanks.

![2019-02-PDFOneJava-USBTokenSign-1](https://user-images.githubusercontent.com/15624834/100862630-656a6e00-34b9-11eb-91a2-2e978f7c99d0.png)

**Comment by LudovicRousseau** [comment]
https://ludovicrousseau.blogspot.com/2020/11/how-to-get-smart-card-support.html
