### ISSUE TITLE
Support pre-built versions for Windows

### ISSUE THREAD

**Issue by danizen** [LudovicRousseau/PyKCS11#84]
# Your system information

* Operating system used: Windows 10
* PyKCS11 version: 1.5.7
* Python version: 3.6.9
* PKCS#11 library used: ActiveClient -  C:\Program Files\HID Global\ActivClient\apkcs211.dll

# Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen.

My down stream users should be able to install "nlmfedcred" which depends on PyKCS11 without having Visual C++ Community installed.

Describe what _did_ happen.

I tried it, and then built a version of PyKCS11.  I then put this in my local Artifactory so my users could get it.  However, my solution for federated login to AWS via PIV is now so good that NIH central wants to take a look at it.  If you can build some version of PyKCS11 with Visual Studio 14.0, and then upload to PyPI, that would be so great!

# Steps for reproducing this issue:

1.  
2.  
3.

**Comment by LudovicRousseau** [comment]
Maybe have a look at https://ci.appveyor.com/project/LudovicRousseau/pykcs11

The versions for Python 3.6 x86_64 are at https://ci.appveyor.com/project/LudovicRousseau/pykcs11/build/job/66p9ix2h79b2l4bl/artifacts

Do you need something else?

**Comment by danizen** [comment]
I think it has been awhile since I built PyKCS11.  I forgot that I needed to install swig.   I've now built-it successfully with version 1.5.10, and verified my code still works.

Also, checking on the PyPI server, I don't see a built version of PyKCS11 - I think I had better double check who got this and how they got it.

**Comment by danizen** [comment]
I'll leave this open for your comments, but consider this low priority for now anyway.

**Comment by LudovicRousseau** [comment]
There are pre-build installers for Windows on https://pypi.org/project/PyKCS11/#files
But no version for Python 3.6. This is an old version of Python.
