### ISSUE TITLE
Problems installing PyKCS11 in virtual environment

### ISSUE THREAD

**Issue by renanaferreira** [LudovicRousseau/PyKCS11#86]
# Your system information

* Operating system used: ubuntu 18.04.5
* PyKCS11 version: 11.5.9
* Python version: 3.6.9
* PKCS#11 library used: I do not know what you mean here

# Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen.
I am using PyKCS11 in a virtual environmnent, I wanted to install it to use on my university project.

Describe what _did_ happen.
When I try to install the dependency on the venv, I get the following error:

Building wheels for collected packages: PyKCS11
  Building wheel for PyKCS11 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/renan/Documents/Cadeiras/SIO/Projetos/proj0203/SIO_PROJ0203/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4szgonjg/pykcs11_0f65eeb5ea1b4344869c6a735e8162eb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4szgonjg/pykcs11_0f65eeb5ea1b4344869c6a735e8162eb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-swimoynf
       cwd: /tmp/pip-install-4szgonjg/pykcs11_0f65eeb5ea1b4344869c6a735e8162eb/
  Complete output (8 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'PyKCS11._LowLevel' extension
  swigging src/pykcs11.i to src/pykcs11_wrap.cpp
  swig -python -c++ -o src/pykcs11_wrap.cpp src/pykcs11.i
  unable to execute 'swig': No such file or directory
  error: command 'swig' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for PyKCS11
  Running setup.py clean for PyKCS11
Failed to build PyKCS11
Installing collected packages: PyKCS11
    Running setup.py install for PyKCS11 ... error
    ERROR: Command errored out with exit status 1:
     command: /home/renan/Documents/Cadeiras/SIO/Projetos/proj0203/SIO_PROJ0203/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4szgonjg/pykcs11_0f65eeb5ea1b4344869c6a735e8162eb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4szgonjg/pykcs11_0f65eeb5ea1b4344869c6a735e8162eb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7bjecvol/install-record.txt --single-version-externally-managed --compile --install-headers /home/renan/Documents/Cadeiras/SIO/Projetos/proj0203/SIO_PROJ0203/venv/include/site/python3.6/PyKCS11
         cwd: /tmp/pip-install-4szgonjg/pykcs11_0f65eeb5ea1b4344869c6a735e8162eb/
    Complete output (8 lines):
    running install
    running build
    running build_ext
    building 'PyKCS11._LowLevel' extension
    swigging src/pykcs11.i to src/pykcs11_wrap.cpp
    swig -python -c++ -o src/pykcs11_wrap.cpp src/pykcs11.i
    unable to execute 'swig': No such file or directory
    error: command 'swig' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/renan/Documents/Cadeiras/SIO/Projetos/proj0203/SIO_PROJ0203/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4szgonjg/pykcs11_0f65eeb5ea1b4344869c6a735e8162eb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4szgonjg/pykcs11_0f65eeb5ea1b4344869c6a735e8162eb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7bjecvol/install-record.txt --single-version-externally-managed --compile --install-headers /home/renan/Documents/Cadeiras/SIO/Projetos/proj0203/SIO_PROJ0203/venv/include/site/python3.6/PyKCS11 Check the logs for full command output.

# Steps for reproducing this issue:

1.  add the following dependency in a text document: PyKCS11==1.5.9
2.  execute pip3 install -r 'path'

**Comment by Jpfonseca** [comment]
The answer can be similar to this one :  
https://github.com/LudovicRousseau/PyKCS11/issues/71#issuecomment-610506691
