### ISSUE TITLE
ACS ACR39U ICC Reader - newbie problem with using  PyKCS11

### ISSUE THREAD

**Issue by sq5rix** [LudovicRousseau/PyKCS11#92]
# Your system information

* Operating system used: arch linux
* PyKCS11 version: current
* Python version: 3.9
* PKCS#11 library used: no idea

I installed my card reader:
$ pkcs11-tool -L
Available slots:
Slot 0 (0x0): ACS ACR39U ICC Reader 00 00
  (token not recognized)

also my pcsc_scan works:
$ pcsc_scan
Using reader plug'n play mechanism
Scanning present readers...
0: ACS ACR39U ICC Reader 00 00
.... 
Possibly identified card (using /home/tom/.cache/smartcard_list.txt):
3B DD 96 FF 81 31 FE 45 80 59 5F 53 74 64 5F 49 6E 69 74 81 05 9B

I installed PyKCS11 from repo (make, sudo make install)

I tried to run this code:

import PyKCS11
pkcs11 = PyKCS11.PyKCS11Lib()
pkcs11.load()

I get error:
PyKCS11.PyKCS11Error: Load (No PKCS11 library specified (set PYKCS11LIB env variable))  

Please point me what library should I install and use.

**Comment by LudovicRousseau** [comment]
Everything is in the error message: **set PYKCS11LIB env variable**
See also https://pkcs11wrap.sourceforge.io/api/api.html?highlight=load#PyKCS11.PyKCS11Lib.load

If OpenSC does NOT recognize your card then PyKCS11 will not work.
