### ISSUE TITLE
Import PKCS#11 3.0 header

### ISSUE THREAD

**Issue by bgermann** [LudovicRousseau/PyKCS11#96]
OpenSC has updated their pkcs11.h to support PKCS#11 3.0. Please update the header file.

**Comment by LudovicRousseau** [comment]
What exactly is missing (for you) in PyKCS11?

**Comment by LudovicRousseau** [comment]
@bgermann No news?

**Comment by LudovicRousseau** [comment]
No news since 1 year.
Closing.
