### ISSUE TITLE
What version of the standard does this library support?

### ISSUE THREAD

**Issue by AFlowOfCode** [LudovicRousseau/PyKCS11#98]
I could not find any information specifying which version of the PKCS#11 standard is supported by this library. I did find a reference to 2.40 in the note for [PyKCS11 1.5.9](https://github.com/LudovicRousseau/PyKCS11/releases/tag/1.5.9), but that is all.

Does this library encompass full 3.0 support of the specification? If not, what is the latest version fully supported?

As of 15 June 2020 v3.0 is [released](https://www.oasis-open.org/2020/07/22/four-pkcs-11-oasis-standards-published/)
As of 11 August 2022 v3.1 is [released](https://www.oasis-open.org/2022/08/15/pkcs-11-specification-v3-1-from-pkcs-11-tc-approved-as-a-committee-specification/)

Thank you!

Edit: I did also find a reference to 3.0 in the note [here](https://github.com/LudovicRousseau/PyKCS11/releases/tag/1.5.8). So it seems like 3.0 may be supported. I think it would be useful to make a note of the spec version in the readme or the documentation site.

**Comment by LudovicRousseau** [comment]
Good question. I have no idea.

If something is missing for you please provide a patch or some help to implement it.
